// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "C:/Users/ArzhangJunior/Desktop/HLS/StepGen/stepGen.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "C:/Users/ArzhangJunior/Desktop/HLS/StepGen/stepGen.cpp"




#ifndef HLS_FASTSIM
#include "apatb_stepGen.h"
#endif
#define stepGen(...) AESL_ORIG_DUT_stepGen(__VA_ARGS__)
#4 "C:/Users/ArzhangJunior/Desktop/HLS/StepGen/stepGen.cpp"
void stepGen (unsigned int out_vec[256])
{
#pragma HLS INTERFACE s_axilite port=out_vec
#pragma HLS INTERFACE s_axilite port=return bundle=CRTL_BUS



 for (int idx = 0; idx < 256; idx++)
 {
  if(idx % 4 == 0 || idx % 4 == 1)
  {
   out_vec[idx] = 40960;
  }
  else
  {
   out_vec[idx] = 24576;
  }

 }
}
#undef stepGen

#23 "C:/Users/ArzhangJunior/Desktop/HLS/StepGen/stepGen.cpp"
