// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sinGen_sinf_or_cosf.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sinGen_sinf_or_cosf::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sinGen_sinf_or_cosf::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st1_fsm_0 = "1";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st2_fsm_1 = "10";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st3_fsm_2 = "100";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st4_fsm_3 = "1000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st5_fsm_4 = "10000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st6_fsm_5 = "100000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<17> sinGen_sinf_or_cosf::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sinGen_sinf_or_cosf::ap_const_lv1_1 = "1";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_1 = "1";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_2 = "10";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_3 = "11";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_4 = "100";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_5 = "101";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_6 = "110";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_7 = "111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_8 = "1000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_9 = "1001";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_E = "1110";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_F = "1111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_1F = "11111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_17 = "10111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_1E = "11110";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_7E = "1111110";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_C2 = "11000010";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_3F = "111111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_1D = "11101";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_63 = "1100011";
const sc_lv<23> sinGen_sinf_or_cosf::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_13 = "10011";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_43 = "1000011";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_44 = "1000100";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_46 = "1000110";
const sc_lv<3> sinGen_sinf_or_cosf::ap_const_lv3_0 = "000";
const sc_lv<49> sinGen_sinf_or_cosf::ap_const_lv49_0 = "0000000000000000000000000000000000000000000000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_30 = "110000";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_83 = "10000011";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_0 = "00000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_12 = "10010";
const sc_lv<13> sinGen_sinf_or_cosf::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_11 = "10001";
const sc_lv<8> sinGen_sinf_or_cosf::ap_const_lv8_FF = "11111111";
const sc_lv<9> sinGen_sinf_or_cosf::ap_const_lv9_0 = "000000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_18 = "11000";
const sc_lv<1> sinGen_sinf_or_cosf::ap_const_lv1_0 = "0";
const sc_lv<31> sinGen_sinf_or_cosf::ap_const_lv31_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_10 = "10000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_27 = "100111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_3D = "111101";
const sc_lv<31> sinGen_sinf_or_cosf::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> sinGen_sinf_or_cosf::ap_const_lv32_3F800000 = "111111100000000000000000000000";

sinGen_sinf_or_cosf::sinGen_sinf_or_cosf(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hls_ref_4oPi_table_100_V_U = new sinGen_sinf_or_cosf_hls_ref_4oPi_table_100_V("hls_ref_4oPi_table_100_V_U");
    hls_ref_4oPi_table_100_V_U->clk(ap_clk);
    hls_ref_4oPi_table_100_V_U->reset(ap_rst);
    hls_ref_4oPi_table_100_V_U->address0(hls_ref_4oPi_table_100_V_address0);
    hls_ref_4oPi_table_100_V_U->ce0(hls_ref_4oPi_table_100_V_ce0);
    hls_ref_4oPi_table_100_V_U->q0(hls_ref_4oPi_table_100_V_q0);
    hls_sin_cos_K0_V_U = new sinGen_sinf_or_cosf_hls_sin_cos_K0_V("hls_sin_cos_K0_V_U");
    hls_sin_cos_K0_V_U->clk(ap_clk);
    hls_sin_cos_K0_V_U->reset(ap_rst);
    hls_sin_cos_K0_V_U->address0(hls_sin_cos_K0_V_address0);
    hls_sin_cos_K0_V_U->ce0(hls_sin_cos_K0_V_ce0);
    hls_sin_cos_K0_V_U->q0(hls_sin_cos_K0_V_q0);
    hls_sin_cos_K1_V_U = new sinGen_sinf_or_cosf_hls_sin_cos_K1_V("hls_sin_cos_K1_V_U");
    hls_sin_cos_K1_V_U->clk(ap_clk);
    hls_sin_cos_K1_V_U->reset(ap_rst);
    hls_sin_cos_K1_V_U->address0(hls_sin_cos_K1_V_address0);
    hls_sin_cos_K1_V_U->ce0(hls_sin_cos_K1_V_ce0);
    hls_sin_cos_K1_V_U->q0(hls_sin_cos_K1_V_q0);
    hls_sin_cos_K2_V_U = new sinGen_sinf_or_cosf_hls_sin_cos_K2_V("hls_sin_cos_K2_V_U");
    hls_sin_cos_K2_V_U->clk(ap_clk);
    hls_sin_cos_K2_V_U->reset(ap_rst);
    hls_sin_cos_K2_V_U->address0(hls_sin_cos_K2_V_address0);
    hls_sin_cos_K2_V_U->ce0(hls_sin_cos_K2_V_ce0);
    hls_sin_cos_K2_V_U->q0(hls_sin_cos_K2_V_q0);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222 = new sinGen_big_mult_v3small_71_24_17_s("grp_sinGen_big_mult_v3small_71_24_17_s_fu_222");
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_clk(ap_clk);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_rst(ap_rst);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_start(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_done(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_idle(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_idle);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_ready(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_ready);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->a_V(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->b_V(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V);
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222->ap_return(grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return);
    grp_sinGen_my_to_float_31_1_s_fu_228 = new sinGen_my_to_float_31_1_s("grp_sinGen_my_to_float_31_1_s_fu_228");
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_clk(ap_clk);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_rst(ap_rst);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_start(grp_sinGen_my_to_float_31_1_s_fu_228_ap_start);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_done(grp_sinGen_my_to_float_31_1_s_fu_228_ap_done);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_idle(grp_sinGen_my_to_float_31_1_s_fu_228_ap_idle);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_ready(grp_sinGen_my_to_float_31_1_s_fu_228_ap_ready);
    grp_sinGen_my_to_float_31_1_s_fu_228->in_V(grp_sinGen_my_to_float_31_1_s_fu_228_in_V);
    grp_sinGen_my_to_float_31_1_s_fu_228->prescale(grp_sinGen_my_to_float_31_1_s_fu_228_prescale);
    grp_sinGen_my_to_float_31_1_s_fu_228->ap_return(grp_sinGen_my_to_float_31_1_s_fu_228_ap_return);
    sinGen_mux_8to1_sel3_1_1_U6 = new sinGen_mux_8to1_sel3_1_1<1,1,1,1,1,1,1,1,1,1,3,1>("sinGen_mux_8to1_sel3_1_1_U6");
    sinGen_mux_8to1_sel3_1_1_U6->din1(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U6->din2(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U6->din3(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U6->din4(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U6->din5(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U6->din6(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U6->din7(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U6->din8(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U6->din9(p_Val2_31_reg_1044);
    sinGen_mux_8to1_sel3_1_1_U6->dout(tmp_fu_598_p10);
    sinGen_mux_8to1_sel3_1_1_U7 = new sinGen_mux_8to1_sel3_1_1<1,1,1,1,1,1,1,1,1,1,3,1>("sinGen_mux_8to1_sel3_1_1_U7");
    sinGen_mux_8to1_sel3_1_1_U7->din1(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U7->din2(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U7->din3(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U7->din4(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U7->din5(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U7->din6(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U7->din7(ap_const_lv1_1);
    sinGen_mux_8to1_sel3_1_1_U7->din8(ap_const_lv1_0);
    sinGen_mux_8to1_sel3_1_1_U7->din9(p_Val2_31_reg_1044);
    sinGen_mux_8to1_sel3_1_1_U7->dout(tmp_s_fu_625_p10);
    sinGen_mux_16to1_sel4_1_1_U8 = new sinGen_mux_16to1_sel4_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("sinGen_mux_16to1_sel4_1_1_U8");
    sinGen_mux_16to1_sel4_1_1_U8->din1(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din2(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din3(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din4(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din5(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din6(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din7(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din8(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din9(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din10(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din11(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din12(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din13(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U8->din14(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din15(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din16(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U8->din17(p_Result_19_fu_703_p3);
    sinGen_mux_16to1_sel4_1_1_U8->dout(tmp_11_fu_709_p18);
    sinGen_mux_16to1_sel4_1_1_U9 = new sinGen_mux_16to1_sel4_1_1<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("sinGen_mux_16to1_sel4_1_1_U9");
    sinGen_mux_16to1_sel4_1_1_U9->din1(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din2(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din3(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din4(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din5(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din6(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din7(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din8(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din9(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din10(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din11(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din12(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din13(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din14(ap_const_lv1_1);
    sinGen_mux_16to1_sel4_1_1_U9->din15(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din16(ap_const_lv1_0);
    sinGen_mux_16to1_sel4_1_1_U9->din17(p_Result_19_fu_703_p3);
    sinGen_mux_16to1_sel4_1_1_U9->dout(tmp_12_fu_747_p18);
    sinGen_mul_32s_31ns_62_6_U10 = new sinGen_mul_32s_31ns_62_6<1,6,32,31,62>("sinGen_mul_32s_31ns_62_6_U10");
    sinGen_mul_32s_31ns_62_6_U10->clk(ap_clk);
    sinGen_mul_32s_31ns_62_6_U10->reset(ap_rst);
    sinGen_mul_32s_31ns_62_6_U10->din0(r_V_reg_1188);
    sinGen_mul_32s_31ns_62_6_U10->din1(grp_fu_887_p1);
    sinGen_mul_32s_31ns_62_6_U10->ce(grp_fu_887_ce);
    sinGen_mul_32s_31ns_62_6_U10->dout(grp_fu_887_p2);
    sinGen_mul_mul_23s_17ns_40_1_U11 = new sinGen_mul_mul_23s_17ns_40_1<1,1,23,17,40>("sinGen_mul_mul_23s_17ns_40_1_U11");
    sinGen_mul_mul_23s_17ns_40_1_U11->din0(hls_sin_cos_K1_V_load_reg_1168);
    sinGen_mul_mul_23s_17ns_40_1_U11->din1(p_Val2_5_fu_979_p1);
    sinGen_mul_mul_23s_17ns_40_1_U11->dout(p_Val2_5_fu_979_p2);
    sinGen_mul_mul_17ns_15s_32_1_U12 = new sinGen_mul_mul_17ns_15s_32_1<1,1,17,15,32>("sinGen_mul_mul_17ns_15s_32_1_U12");
    sinGen_mul_mul_17ns_15s_32_1_U12->din0(p_Val2_6_fu_986_p0);
    sinGen_mul_mul_17ns_15s_32_1_U12->din1(hls_sin_cos_K2_V_load_reg_1173);
    sinGen_mul_mul_17ns_15s_32_1_U12->dout(p_Val2_6_fu_986_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_467_p2);
    sensitive << ( storemerge_i_fu_392_p3 );
    sensitive << ( tmp_31_i_fu_463_p1 );

    SC_METHOD(thread_Mx_zeros_V_fu_432_p1);
    sensitive << ( val_assign_fu_424_p3 );

    SC_METHOD(thread_OP1_V_3_fu_803_p1);
    sensitive << ( tmp_1_reg_1113 );

    SC_METHOD(thread_addr_V_fu_272_p3);
    sensitive << ( closepath_fu_260_p2 );
    sensitive << ( p_op_i_fu_266_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( tmp_16_fu_967_p2 );
    sensitive << ( sel_tmp4_fu_960_p3 );
    sensitive << ( sel_tmp2_fu_956_p1 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_123);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_142);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_180);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_192);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_203);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_212);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_223);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_234);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_587);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_223 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_234 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_587 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_35 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_93 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_142 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_180 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_192 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_203 );

    SC_METHOD(thread_closepath_fu_260_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( loc_V_fu_246_p4 );

    SC_METHOD(thread_cos_basis_fu_654_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_cos_basis_fu_654_p3);
    sensitive << ( tmp_s_fu_625_p10 );
    sensitive << ( cos_basis_fu_654_p0 );
    sensitive << ( tmp_4_fu_619_p2 );

    SC_METHOD(thread_grp_fu_887_ce);

    SC_METHOD(thread_grp_fu_887_p1);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( grp_fu_887_p10 );

    SC_METHOD(thread_grp_fu_887_p10);
    sensitive << ( p_Mx_V_ret_reg_1123 );

    SC_METHOD(thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V);
    sensitive << ( Med_V_reg_1033 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start);
    sensitive << ( grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V);
    sensitive << ( p_Result_13_reg_1028 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_sinGen_my_to_float_31_1_s_fu_228_ap_start);
    sensitive << ( grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_sinGen_my_to_float_31_1_s_fu_228_in_V);
    sensitive << ( p_0_reg_1203 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_grp_sinGen_my_to_float_31_1_s_fu_228_prescale);
    sensitive << ( r_V_1_reg_1208 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_hls_ref_4oPi_table_100_V_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_5_i_i_fu_290_p1 );

    SC_METHOD(thread_hls_ref_4oPi_table_100_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_hls_sin_cos_K0_V_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_8_fu_696_p1 );

    SC_METHOD(thread_hls_sin_cos_K0_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_hls_sin_cos_K1_V_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_8_fu_696_p1 );

    SC_METHOD(thread_hls_sin_cos_K1_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_hls_sin_cos_K2_V_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_8_fu_696_p1 );

    SC_METHOD(thread_hls_sin_cos_K2_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_loc_V_1_fu_256_p1);
    sensitive << ( p_Val2_28_fu_234_p1 );

    SC_METHOD(thread_loc_V_fu_246_p4);
    sensitive << ( p_Val2_28_fu_234_p1 );

    SC_METHOD(thread_not_do_cos_fu_662_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_not_do_cos_fu_662_p2);
    sensitive << ( not_do_cos_fu_662_p0 );

    SC_METHOD(thread_or_cond_fu_486_p2);
    sensitive << ( tmp_15_reg_1038 );
    sensitive << ( tmp_14_fu_481_p2 );

    SC_METHOD(thread_p_Ex_V_ret_fu_682_p3);
    sensitive << ( Ex_V_reg_1071 );
    sensitive << ( cos_basis_fu_654_p3 );

    SC_METHOD(thread_p_Mx_V_ret_fu_689_p3);
    sensitive << ( p_Val2_32_reg_1095 );
    sensitive << ( cos_basis_fu_654_p3 );

    SC_METHOD(thread_p_Result_12_fu_925_p2);
    sensitive << ( tmp_13_reg_1143 );
    sensitive << ( p_Result_18_fu_917_p3 );

    SC_METHOD(thread_p_Result_13_fu_299_p3);
    sensitive << ( loc_V_1_reg_1006 );

    SC_METHOD(thread_p_Result_14_fu_399_p3);
    sensitive << ( p_Result_i2_i_reg_1056 );

    SC_METHOD(thread_p_Result_15_fu_406_p4);
    sensitive << ( p_Result_14_fu_399_p3 );

    SC_METHOD(thread_p_Result_16_fu_416_p3);
    sensitive << ( p_Result_15_fu_406_p4 );

    SC_METHOD(thread_p_Result_17_fu_674_p3);
    sensitive << ( sin_basis_fu_668_p2 );
    sensitive << ( p_Result_s_40_fu_568_p4 );

    SC_METHOD(thread_p_Result_18_fu_917_p3);
    sensitive << ( p_Val2_25_fu_914_p1 );

    SC_METHOD(thread_p_Result_19_fu_703_p3);
    sensitive << ( p_Result_s_reg_993 );
    sensitive << ( p_Val2_31_reg_1044 );

    SC_METHOD(thread_p_Result_20_fu_930_p3);
    sensitive << ( p_Result_s_reg_993 );

    SC_METHOD(thread_p_Result_21_fu_941_p3);
    sensitive << ( p_Result_12_fu_925_p2 );
    sensitive << ( tmp_25_fu_937_p1 );

    SC_METHOD(thread_p_Result_s_40_fu_568_p4);
    sensitive << ( p_Val2_0_i245_in_i_fu_561_p3 );

    SC_METHOD(thread_p_Val2_0_i245_in_i_fu_561_p3);
    sensitive << ( isNeg_reg_1077 );
    sensitive << ( tmp_35_i_cast_fu_551_p1 );
    sensitive << ( tmp_37_i_fu_555_p2 );

    SC_METHOD(thread_p_Val2_14_fu_332_p4);
    sensitive << ( grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return );

    SC_METHOD(thread_p_Val2_19_fu_369_p3);
    sensitive << ( p_Val2_14_fu_332_p4 );
    sensitive << ( tmp_20_fu_359_p1 );
    sensitive << ( p_Val2_i_fu_363_p2 );

    SC_METHOD(thread_p_Val2_22_fu_440_p2);
    sensitive << ( p_Val2_19_reg_1051 );
    sensitive << ( tmp_28_i_fu_436_p1 );

    SC_METHOD(thread_p_Val2_25_fu_914_p1);
    sensitive << ( resultf_reg_1213 );

    SC_METHOD(thread_p_Val2_28_fu_234_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_p_Val2_31_fu_352_p3);
    sensitive << ( closepath_reg_1012 );
    sensitive << ( tmp_27_i_fu_342_p4 );

    SC_METHOD(thread_p_Val2_32_fu_516_p2);
    sensitive << ( p_Val2_23_reg_1061 );
    sensitive << ( tmp_30_i_fu_513_p1 );

    SC_METHOD(thread_p_Val2_3_fu_806_p0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( OP1_V_3_fu_803_p1 );

    SC_METHOD(thread_p_Val2_3_fu_806_p1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( OP1_V_3_fu_803_p1 );

    SC_METHOD(thread_p_Val2_3_fu_806_p2);
    sensitive << ( p_Val2_3_fu_806_p0 );
    sensitive << ( p_Val2_3_fu_806_p1 );

    SC_METHOD(thread_p_Val2_5_fu_979_p1);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( p_Val2_5_fu_979_p10 );

    SC_METHOD(thread_p_Val2_5_fu_979_p10);
    sensitive << ( p_Val2_2_reg_1108 );

    SC_METHOD(thread_p_Val2_6_fu_986_p0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( p_Val2_6_fu_986_p00 );

    SC_METHOD(thread_p_Val2_6_fu_986_p00);
    sensitive << ( tmp_3_reg_1158 );

    SC_METHOD(thread_p_Val2_7_fu_852_p3);
    sensitive << ( p_Val2_s_reg_1163 );

    SC_METHOD(thread_p_Val2_8_fu_866_p2);
    sensitive << ( tmp_9_fu_859_p1 );
    sensitive << ( tmp_10_fu_863_p1 );

    SC_METHOD(thread_p_Val2_i_fu_363_p2);
    sensitive << ( p_Val2_14_fu_332_p4 );

    SC_METHOD(thread_p_i_fu_387_p2);
    sensitive << ( loc_V_reg_999 );

    SC_METHOD(thread_p_op_i_fu_266_p2);
    sensitive << ( loc_V_fu_246_p4 );

    SC_METHOD(thread_r_V_1_fu_907_p2);
    sensitive << ( rhs_V_fu_904_p1 );

    SC_METHOD(thread_r_V_3_fu_310_p2);
    sensitive << ( hls_ref_4oPi_table_100_V_q0 );
    sensitive << ( tmp_7_i_i_fu_307_p1 );

    SC_METHOD(thread_r_V_fu_875_p2);
    sensitive << ( p_Val2_8_fu_866_p2 );
    sensitive << ( tmp_18_cast_fu_872_p1 );

    SC_METHOD(thread_rhs_V_fu_904_p1);
    sensitive << ( p_Ex_V_ret_reg_1118 );

    SC_METHOD(thread_sel_tmp1_fu_793_p2);
    sensitive << ( or_cond_reg_1083 );
    sensitive << ( not_do_cos_fu_662_p2 );

    SC_METHOD(thread_sel_tmp2_fu_956_p1);
    sensitive << ( sel_tmp2_v_fu_949_p3 );

    SC_METHOD(thread_sel_tmp2_v_fu_949_p3);
    sensitive << ( sel_tmp1_reg_1148 );
    sensitive << ( p_Result_20_fu_930_p3 );
    sensitive << ( p_Result_21_fu_941_p3 );

    SC_METHOD(thread_sel_tmp3_fu_798_p1);
    sensitive << ( do_cos );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_sel_tmp3_fu_798_p2);
    sensitive << ( or_cond_reg_1083 );
    sensitive << ( sel_tmp3_fu_798_p1 );

    SC_METHOD(thread_sel_tmp4_fu_960_p3);
    sensitive << ( sel_tmp6_reg_1089 );

    SC_METHOD(thread_sel_tmp5_demorgan_fu_496_p2);
    sensitive << ( tmp_15_reg_1038 );
    sensitive << ( tmp_14_fu_481_p2 );

    SC_METHOD(thread_sel_tmp5_fu_501_p2);
    sensitive << ( sel_tmp5_demorgan_fu_496_p2 );

    SC_METHOD(thread_sel_tmp6_fu_507_p2);
    sensitive << ( tmp_i_fu_491_p2 );
    sensitive << ( sel_tmp5_fu_501_p2 );

    SC_METHOD(thread_sh_assign_1_i_cast8_fu_537_p1);
    sensitive << ( sh_assign_reg_1102 );

    SC_METHOD(thread_sh_assign_1_i_cast_fu_540_p1);
    sensitive << ( sh_assign_reg_1102 );

    SC_METHOD(thread_sh_assign_fu_530_p3);
    sensitive << ( isNeg_reg_1077 );
    sensitive << ( sh_i_cast_fu_521_p1 );
    sensitive << ( tmp_33_i_fu_524_p2 );

    SC_METHOD(thread_sh_i_cast_fu_521_p1);
    sensitive << ( Ex_V_reg_1071 );

    SC_METHOD(thread_sin_basis_fu_668_p2);
    sensitive << ( tmp_6_fu_646_p3 );
    sensitive << ( not_do_cos_fu_662_p2 );

    SC_METHOD(thread_storemerge_i_fu_392_p3);
    sensitive << ( closepath_reg_1012 );
    sensitive << ( p_i_fu_387_p2 );

    SC_METHOD(thread_tmp_10_fu_863_p1);
    sensitive << ( tmp_5_reg_1178 );

    SC_METHOD(thread_tmp_13_fu_785_p3);
    sensitive << ( cos_basis_fu_654_p3 );
    sensitive << ( tmp_11_fu_709_p18 );
    sensitive << ( tmp_12_fu_747_p18 );

    SC_METHOD(thread_tmp_14_fu_481_p2);
    sensitive << ( loc_V_reg_999 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp_15_fu_327_p2);
    sensitive << ( loc_V_1_reg_1006 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_16_fu_967_p2);
    sensitive << ( sel_tmp6_reg_1089 );
    sensitive << ( sel_tmp3_reg_1153 );

    SC_METHOD(thread_tmp_18_cast_fu_872_p1);
    sensitive << ( tmp_7_reg_1183 );

    SC_METHOD(thread_tmp_19_fu_295_p1);
    sensitive << ( addr_V_fu_272_p3 );

    SC_METHOD(thread_tmp_20_fu_359_p1);
    sensitive << ( p_Val2_31_fu_352_p3 );

    SC_METHOD(thread_tmp_25_fu_937_p1);
    sensitive << ( p_Val2_25_fu_914_p1 );

    SC_METHOD(thread_tmp_27_i_fu_342_p4);
    sensitive << ( grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return );

    SC_METHOD(thread_tmp_28_i_fu_436_p1);
    sensitive << ( Mx_zeros_V_fu_432_p1 );

    SC_METHOD(thread_tmp_2_fu_280_p4);
    sensitive << ( addr_V_fu_272_p3 );

    SC_METHOD(thread_tmp_30_i_fu_513_p1);
    sensitive << ( tmp_22_reg_1066 );

    SC_METHOD(thread_tmp_31_i_fu_463_p1);
    sensitive << ( Mx_zeros_V_fu_432_p1 );

    SC_METHOD(thread_tmp_33_i_fu_524_p2);
    sensitive << ( sh_i_cast_fu_521_p1 );

    SC_METHOD(thread_tmp_34_i_fu_543_p1);
    sensitive << ( p_Val2_32_reg_1095 );

    SC_METHOD(thread_tmp_35_i_cast_fu_551_p1);
    sensitive << ( tmp_35_i_fu_546_p2 );

    SC_METHOD(thread_tmp_35_i_fu_546_p2);
    sensitive << ( p_Val2_32_reg_1095 );
    sensitive << ( sh_assign_1_i_cast_fu_540_p1 );

    SC_METHOD(thread_tmp_37_i_fu_555_p2);
    sensitive << ( tmp_34_i_fu_543_p1 );
    sensitive << ( sh_assign_1_i_cast8_fu_537_p1 );

    SC_METHOD(thread_tmp_4_fu_619_p2);
    sensitive << ( tmp_fu_598_p10 );

    SC_METHOD(thread_tmp_5_i_i_fu_290_p1);
    sensitive << ( tmp_2_fu_280_p4 );

    SC_METHOD(thread_tmp_6_fu_646_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp_6_fu_646_p3);
    sensitive << ( tmp_fu_598_p10 );
    sensitive << ( tmp_6_fu_646_p0 );
    sensitive << ( tmp_s_fu_625_p10 );

    SC_METHOD(thread_tmp_7_i_i_fu_307_p1);
    sensitive << ( tmp_19_reg_1023 );

    SC_METHOD(thread_tmp_8_fu_696_p1);
    sensitive << ( p_Result_17_fu_674_p3 );

    SC_METHOD(thread_tmp_9_fu_859_p1);
    sensitive << ( p_Val2_7_fu_852_p3 );

    SC_METHOD(thread_tmp_i_fu_491_p2);
    sensitive << ( loc_V_reg_999 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_val_assign_fu_424_p3);
    sensitive << ( p_Result_16_fu_416_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done );
    sensitive << ( grp_sinGen_my_to_float_31_1_s_fu_228_ap_done );

    ap_CS_fsm = "00000000000000001";
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sinGen_sinf_or_cosf_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, do_cos, "(port)do_cos");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_35, "ap_sig_bdd_35");
    sc_trace(mVcdFile, hls_ref_4oPi_table_100_V_address0, "hls_ref_4oPi_table_100_V_address0");
    sc_trace(mVcdFile, hls_ref_4oPi_table_100_V_ce0, "hls_ref_4oPi_table_100_V_ce0");
    sc_trace(mVcdFile, hls_ref_4oPi_table_100_V_q0, "hls_ref_4oPi_table_100_V_q0");
    sc_trace(mVcdFile, hls_sin_cos_K0_V_address0, "hls_sin_cos_K0_V_address0");
    sc_trace(mVcdFile, hls_sin_cos_K0_V_ce0, "hls_sin_cos_K0_V_ce0");
    sc_trace(mVcdFile, hls_sin_cos_K0_V_q0, "hls_sin_cos_K0_V_q0");
    sc_trace(mVcdFile, hls_sin_cos_K1_V_address0, "hls_sin_cos_K1_V_address0");
    sc_trace(mVcdFile, hls_sin_cos_K1_V_ce0, "hls_sin_cos_K1_V_ce0");
    sc_trace(mVcdFile, hls_sin_cos_K1_V_q0, "hls_sin_cos_K1_V_q0");
    sc_trace(mVcdFile, hls_sin_cos_K2_V_address0, "hls_sin_cos_K2_V_address0");
    sc_trace(mVcdFile, hls_sin_cos_K2_V_ce0, "hls_sin_cos_K2_V_ce0");
    sc_trace(mVcdFile, hls_sin_cos_K2_V_q0, "hls_sin_cos_K2_V_q0");
    sc_trace(mVcdFile, p_Result_s_reg_993, "p_Result_s_reg_993");
    sc_trace(mVcdFile, loc_V_fu_246_p4, "loc_V_fu_246_p4");
    sc_trace(mVcdFile, loc_V_reg_999, "loc_V_reg_999");
    sc_trace(mVcdFile, loc_V_1_fu_256_p1, "loc_V_1_fu_256_p1");
    sc_trace(mVcdFile, loc_V_1_reg_1006, "loc_V_1_reg_1006");
    sc_trace(mVcdFile, closepath_fu_260_p2, "closepath_fu_260_p2");
    sc_trace(mVcdFile, closepath_reg_1012, "closepath_reg_1012");
    sc_trace(mVcdFile, tmp_19_fu_295_p1, "tmp_19_fu_295_p1");
    sc_trace(mVcdFile, tmp_19_reg_1023, "tmp_19_reg_1023");
    sc_trace(mVcdFile, p_Result_13_fu_299_p3, "p_Result_13_fu_299_p3");
    sc_trace(mVcdFile, p_Result_13_reg_1028, "p_Result_13_reg_1028");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, Med_V_reg_1033, "Med_V_reg_1033");
    sc_trace(mVcdFile, tmp_15_fu_327_p2, "tmp_15_fu_327_p2");
    sc_trace(mVcdFile, tmp_15_reg_1038, "tmp_15_reg_1038");
    sc_trace(mVcdFile, p_Val2_31_fu_352_p3, "p_Val2_31_fu_352_p3");
    sc_trace(mVcdFile, p_Val2_31_reg_1044, "p_Val2_31_reg_1044");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done");
    sc_trace(mVcdFile, p_Val2_19_fu_369_p3, "p_Val2_19_fu_369_p3");
    sc_trace(mVcdFile, p_Val2_19_reg_1051, "p_Val2_19_reg_1051");
    sc_trace(mVcdFile, p_Result_i2_i_reg_1056, "p_Result_i2_i_reg_1056");
    sc_trace(mVcdFile, p_Val2_23_reg_1061, "p_Val2_23_reg_1061");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_123, "ap_sig_bdd_123");
    sc_trace(mVcdFile, tmp_22_reg_1066, "tmp_22_reg_1066");
    sc_trace(mVcdFile, Ex_V_fu_467_p2, "Ex_V_fu_467_p2");
    sc_trace(mVcdFile, Ex_V_reg_1071, "Ex_V_reg_1071");
    sc_trace(mVcdFile, isNeg_reg_1077, "isNeg_reg_1077");
    sc_trace(mVcdFile, or_cond_fu_486_p2, "or_cond_fu_486_p2");
    sc_trace(mVcdFile, or_cond_reg_1083, "or_cond_reg_1083");
    sc_trace(mVcdFile, sel_tmp6_fu_507_p2, "sel_tmp6_fu_507_p2");
    sc_trace(mVcdFile, sel_tmp6_reg_1089, "sel_tmp6_reg_1089");
    sc_trace(mVcdFile, p_Val2_32_fu_516_p2, "p_Val2_32_fu_516_p2");
    sc_trace(mVcdFile, p_Val2_32_reg_1095, "p_Val2_32_reg_1095");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_142, "ap_sig_bdd_142");
    sc_trace(mVcdFile, sh_assign_fu_530_p3, "sh_assign_fu_530_p3");
    sc_trace(mVcdFile, sh_assign_reg_1102, "sh_assign_reg_1102");
    sc_trace(mVcdFile, p_Val2_2_reg_1108, "p_Val2_2_reg_1108");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, tmp_1_reg_1113, "tmp_1_reg_1113");
    sc_trace(mVcdFile, p_Ex_V_ret_fu_682_p3, "p_Ex_V_ret_fu_682_p3");
    sc_trace(mVcdFile, p_Ex_V_ret_reg_1118, "p_Ex_V_ret_reg_1118");
    sc_trace(mVcdFile, p_Mx_V_ret_fu_689_p3, "p_Mx_V_ret_fu_689_p3");
    sc_trace(mVcdFile, p_Mx_V_ret_reg_1123, "p_Mx_V_ret_reg_1123");
    sc_trace(mVcdFile, tmp_13_fu_785_p3, "tmp_13_fu_785_p3");
    sc_trace(mVcdFile, tmp_13_reg_1143, "tmp_13_reg_1143");
    sc_trace(mVcdFile, sel_tmp1_fu_793_p2, "sel_tmp1_fu_793_p2");
    sc_trace(mVcdFile, sel_tmp1_reg_1148, "sel_tmp1_reg_1148");
    sc_trace(mVcdFile, sel_tmp3_fu_798_p2, "sel_tmp3_fu_798_p2");
    sc_trace(mVcdFile, sel_tmp3_reg_1153, "sel_tmp3_reg_1153");
    sc_trace(mVcdFile, tmp_3_reg_1158, "tmp_3_reg_1158");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_180, "ap_sig_bdd_180");
    sc_trace(mVcdFile, p_Val2_s_reg_1163, "p_Val2_s_reg_1163");
    sc_trace(mVcdFile, hls_sin_cos_K1_V_load_reg_1168, "hls_sin_cos_K1_V_load_reg_1168");
    sc_trace(mVcdFile, hls_sin_cos_K2_V_load_reg_1173, "hls_sin_cos_K2_V_load_reg_1173");
    sc_trace(mVcdFile, tmp_5_reg_1178, "tmp_5_reg_1178");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_192, "ap_sig_bdd_192");
    sc_trace(mVcdFile, tmp_7_reg_1183, "tmp_7_reg_1183");
    sc_trace(mVcdFile, r_V_fu_875_p2, "r_V_fu_875_p2");
    sc_trace(mVcdFile, r_V_reg_1188, "r_V_reg_1188");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_203, "ap_sig_bdd_203");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_212, "ap_sig_bdd_212");
    sc_trace(mVcdFile, p_0_reg_1203, "p_0_reg_1203");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_223, "ap_sig_bdd_223");
    sc_trace(mVcdFile, r_V_1_fu_907_p2, "r_V_1_fu_907_p2");
    sc_trace(mVcdFile, r_V_1_reg_1208, "r_V_1_reg_1208");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_return, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_return");
    sc_trace(mVcdFile, resultf_reg_1213, "resultf_reg_1213");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_234, "ap_sig_bdd_234");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_done, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_done");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_idle, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_idle");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_ready, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_ready");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_start, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_start");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_idle, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_idle");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_ready, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_ready");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_in_V, "grp_sinGen_my_to_float_31_1_s_fu_228_in_V");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_prescale, "grp_sinGen_my_to_float_31_1_s_fu_228_prescale");
    sc_trace(mVcdFile, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg, "grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg");
    sc_trace(mVcdFile, grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg, "grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_5_i_i_fu_290_p1, "tmp_5_i_i_fu_290_p1");
    sc_trace(mVcdFile, tmp_8_fu_696_p1, "tmp_8_fu_696_p1");
    sc_trace(mVcdFile, p_Val2_28_fu_234_p1, "p_Val2_28_fu_234_p1");
    sc_trace(mVcdFile, p_op_i_fu_266_p2, "p_op_i_fu_266_p2");
    sc_trace(mVcdFile, addr_V_fu_272_p3, "addr_V_fu_272_p3");
    sc_trace(mVcdFile, tmp_2_fu_280_p4, "tmp_2_fu_280_p4");
    sc_trace(mVcdFile, tmp_7_i_i_fu_307_p1, "tmp_7_i_i_fu_307_p1");
    sc_trace(mVcdFile, r_V_3_fu_310_p2, "r_V_3_fu_310_p2");
    sc_trace(mVcdFile, tmp_27_i_fu_342_p4, "tmp_27_i_fu_342_p4");
    sc_trace(mVcdFile, p_Val2_14_fu_332_p4, "p_Val2_14_fu_332_p4");
    sc_trace(mVcdFile, tmp_20_fu_359_p1, "tmp_20_fu_359_p1");
    sc_trace(mVcdFile, p_Val2_i_fu_363_p2, "p_Val2_i_fu_363_p2");
    sc_trace(mVcdFile, p_i_fu_387_p2, "p_i_fu_387_p2");
    sc_trace(mVcdFile, p_Result_14_fu_399_p3, "p_Result_14_fu_399_p3");
    sc_trace(mVcdFile, p_Result_15_fu_406_p4, "p_Result_15_fu_406_p4");
    sc_trace(mVcdFile, p_Result_16_fu_416_p3, "p_Result_16_fu_416_p3");
    sc_trace(mVcdFile, val_assign_fu_424_p3, "val_assign_fu_424_p3");
    sc_trace(mVcdFile, Mx_zeros_V_fu_432_p1, "Mx_zeros_V_fu_432_p1");
    sc_trace(mVcdFile, tmp_28_i_fu_436_p1, "tmp_28_i_fu_436_p1");
    sc_trace(mVcdFile, p_Val2_22_fu_440_p2, "p_Val2_22_fu_440_p2");
    sc_trace(mVcdFile, storemerge_i_fu_392_p3, "storemerge_i_fu_392_p3");
    sc_trace(mVcdFile, tmp_31_i_fu_463_p1, "tmp_31_i_fu_463_p1");
    sc_trace(mVcdFile, tmp_14_fu_481_p2, "tmp_14_fu_481_p2");
    sc_trace(mVcdFile, sel_tmp5_demorgan_fu_496_p2, "sel_tmp5_demorgan_fu_496_p2");
    sc_trace(mVcdFile, tmp_i_fu_491_p2, "tmp_i_fu_491_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_501_p2, "sel_tmp5_fu_501_p2");
    sc_trace(mVcdFile, tmp_30_i_fu_513_p1, "tmp_30_i_fu_513_p1");
    sc_trace(mVcdFile, sh_i_cast_fu_521_p1, "sh_i_cast_fu_521_p1");
    sc_trace(mVcdFile, tmp_33_i_fu_524_p2, "tmp_33_i_fu_524_p2");
    sc_trace(mVcdFile, sh_assign_1_i_cast_fu_540_p1, "sh_assign_1_i_cast_fu_540_p1");
    sc_trace(mVcdFile, tmp_35_i_fu_546_p2, "tmp_35_i_fu_546_p2");
    sc_trace(mVcdFile, tmp_34_i_fu_543_p1, "tmp_34_i_fu_543_p1");
    sc_trace(mVcdFile, sh_assign_1_i_cast8_fu_537_p1, "sh_assign_1_i_cast8_fu_537_p1");
    sc_trace(mVcdFile, tmp_35_i_cast_fu_551_p1, "tmp_35_i_cast_fu_551_p1");
    sc_trace(mVcdFile, tmp_37_i_fu_555_p2, "tmp_37_i_fu_555_p2");
    sc_trace(mVcdFile, p_Val2_0_i245_in_i_fu_561_p3, "p_Val2_0_i245_in_i_fu_561_p3");
    sc_trace(mVcdFile, tmp_fu_598_p10, "tmp_fu_598_p10");
    sc_trace(mVcdFile, tmp_6_fu_646_p0, "tmp_6_fu_646_p0");
    sc_trace(mVcdFile, tmp_s_fu_625_p10, "tmp_s_fu_625_p10");
    sc_trace(mVcdFile, cos_basis_fu_654_p0, "cos_basis_fu_654_p0");
    sc_trace(mVcdFile, tmp_4_fu_619_p2, "tmp_4_fu_619_p2");
    sc_trace(mVcdFile, not_do_cos_fu_662_p0, "not_do_cos_fu_662_p0");
    sc_trace(mVcdFile, tmp_6_fu_646_p3, "tmp_6_fu_646_p3");
    sc_trace(mVcdFile, not_do_cos_fu_662_p2, "not_do_cos_fu_662_p2");
    sc_trace(mVcdFile, sin_basis_fu_668_p2, "sin_basis_fu_668_p2");
    sc_trace(mVcdFile, p_Result_s_40_fu_568_p4, "p_Result_s_40_fu_568_p4");
    sc_trace(mVcdFile, cos_basis_fu_654_p3, "cos_basis_fu_654_p3");
    sc_trace(mVcdFile, p_Result_17_fu_674_p3, "p_Result_17_fu_674_p3");
    sc_trace(mVcdFile, p_Result_19_fu_703_p3, "p_Result_19_fu_703_p3");
    sc_trace(mVcdFile, tmp_11_fu_709_p18, "tmp_11_fu_709_p18");
    sc_trace(mVcdFile, tmp_12_fu_747_p18, "tmp_12_fu_747_p18");
    sc_trace(mVcdFile, sel_tmp3_fu_798_p1, "sel_tmp3_fu_798_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_806_p0, "p_Val2_3_fu_806_p0");
    sc_trace(mVcdFile, OP1_V_3_fu_803_p1, "OP1_V_3_fu_803_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_806_p1, "p_Val2_3_fu_806_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_806_p2, "p_Val2_3_fu_806_p2");
    sc_trace(mVcdFile, p_Val2_5_fu_979_p2, "p_Val2_5_fu_979_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_986_p2, "p_Val2_6_fu_986_p2");
    sc_trace(mVcdFile, p_Val2_7_fu_852_p3, "p_Val2_7_fu_852_p3");
    sc_trace(mVcdFile, tmp_9_fu_859_p1, "tmp_9_fu_859_p1");
    sc_trace(mVcdFile, tmp_10_fu_863_p1, "tmp_10_fu_863_p1");
    sc_trace(mVcdFile, p_Val2_8_fu_866_p2, "p_Val2_8_fu_866_p2");
    sc_trace(mVcdFile, tmp_18_cast_fu_872_p1, "tmp_18_cast_fu_872_p1");
    sc_trace(mVcdFile, grp_fu_887_p1, "grp_fu_887_p1");
    sc_trace(mVcdFile, grp_fu_887_p2, "grp_fu_887_p2");
    sc_trace(mVcdFile, rhs_V_fu_904_p1, "rhs_V_fu_904_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_587, "ap_sig_bdd_587");
    sc_trace(mVcdFile, p_Val2_25_fu_914_p1, "p_Val2_25_fu_914_p1");
    sc_trace(mVcdFile, p_Result_18_fu_917_p3, "p_Result_18_fu_917_p3");
    sc_trace(mVcdFile, p_Result_12_fu_925_p2, "p_Result_12_fu_925_p2");
    sc_trace(mVcdFile, tmp_25_fu_937_p1, "tmp_25_fu_937_p1");
    sc_trace(mVcdFile, p_Result_20_fu_930_p3, "p_Result_20_fu_930_p3");
    sc_trace(mVcdFile, p_Result_21_fu_941_p3, "p_Result_21_fu_941_p3");
    sc_trace(mVcdFile, sel_tmp2_v_fu_949_p3, "sel_tmp2_v_fu_949_p3");
    sc_trace(mVcdFile, tmp_16_fu_967_p2, "tmp_16_fu_967_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_960_p3, "sel_tmp4_fu_960_p3");
    sc_trace(mVcdFile, sel_tmp2_fu_956_p1, "sel_tmp2_fu_956_p1");
    sc_trace(mVcdFile, p_Val2_5_fu_979_p1, "p_Val2_5_fu_979_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_986_p0, "p_Val2_6_fu_986_p0");
    sc_trace(mVcdFile, grp_fu_887_ce, "grp_fu_887_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_887_p10, "grp_fu_887_p10");
    sc_trace(mVcdFile, p_Val2_5_fu_979_p10, "p_Val2_5_fu_979_p10");
    sc_trace(mVcdFile, p_Val2_6_fu_986_p00, "p_Val2_6_fu_986_p00");
#endif

    }
}

sinGen_sinf_or_cosf::~sinGen_sinf_or_cosf() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete hls_ref_4oPi_table_100_V_U;
    delete hls_sin_cos_K0_V_U;
    delete hls_sin_cos_K1_V_U;
    delete hls_sin_cos_K2_V_U;
    delete grp_sinGen_big_mult_v3small_71_24_17_s_fu_222;
    delete grp_sinGen_my_to_float_31_1_s_fu_228;
    delete sinGen_mux_8to1_sel3_1_1_U6;
    delete sinGen_mux_8to1_sel3_1_1_U7;
    delete sinGen_mux_16to1_sel4_1_1_U8;
    delete sinGen_mux_16to1_sel4_1_1_U9;
    delete sinGen_mul_32s_31ns_62_6_U10;
    delete sinGen_mul_mul_23s_17ns_40_1_U11;
    delete sinGen_mul_mul_17ns_15s_32_1_U12;
}

void sinGen_sinf_or_cosf::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
            grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_ready.read())) {
            grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
            grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sinGen_my_to_float_31_1_s_fu_228_ap_ready.read())) {
            grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        Ex_V_reg_1071 = Ex_V_fu_467_p2.read();
        isNeg_reg_1077 = Ex_V_fu_467_p2.read().range(7, 7);
        or_cond_reg_1083 = or_cond_fu_486_p2.read();
        p_Val2_23_reg_1061 = p_Val2_22_fu_440_p2.read().range(48, 18);
        sel_tmp6_reg_1089 = sel_tmp6_fu_507_p2.read();
        tmp_22_reg_1066 = p_Val2_22_fu_440_p2.read().range(17, 17);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        Med_V_reg_1033 = r_V_3_fu_310_p2.read().range(99, 29);
        p_Result_13_reg_1028 = p_Result_13_fu_299_p3.read();
        tmp_15_reg_1038 = tmp_15_fu_327_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        closepath_reg_1012 = closepath_fu_260_p2.read();
        loc_V_1_reg_1006 = loc_V_1_fu_256_p1.read();
        loc_V_reg_999 = p_Val2_28_fu_234_p1.read().range(30, 23);
        p_Result_s_reg_993 = p_Val2_28_fu_234_p1.read().range(31, 31);
        tmp_19_reg_1023 = tmp_19_fu_295_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        hls_sin_cos_K1_V_load_reg_1168 = hls_sin_cos_K1_V_q0.read();
        hls_sin_cos_K2_V_load_reg_1173 = hls_sin_cos_K2_V_q0.read();
        p_Val2_s_reg_1163 = hls_sin_cos_K0_V_q0.read();
        tmp_3_reg_1158 = p_Val2_3_fu_806_p2.read().range(17, 1);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        p_0_reg_1203 = grp_fu_887_p2.read().range(61, 31);
        r_V_1_reg_1208 = r_V_1_fu_907_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        p_Ex_V_ret_reg_1118 = p_Ex_V_ret_fu_682_p3.read();
        p_Mx_V_ret_reg_1123 = p_Mx_V_ret_fu_689_p3.read();
        p_Val2_2_reg_1108 = p_Val2_0_i245_in_i_fu_561_p3.read().range(23, 7);
        sel_tmp1_reg_1148 = sel_tmp1_fu_793_p2.read();
        sel_tmp3_reg_1153 = sel_tmp3_fu_798_p2.read();
        tmp_13_reg_1143 = tmp_13_fu_785_p3.read();
        tmp_1_reg_1113 = p_Val2_0_i245_in_i_fu_561_p3.read().range(23, 15);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done.read()))) {
        p_Result_i2_i_reg_1056 = p_Val2_19_fu_369_p3.read().range(48, 31);
        p_Val2_19_reg_1051 = p_Val2_19_fu_369_p3.read();
        p_Val2_31_reg_1044 = p_Val2_31_fu_352_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        p_Val2_32_reg_1095 = p_Val2_32_fu_516_p2.read();
        sh_assign_reg_1102 = sh_assign_fu_530_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        r_V_reg_1188 = r_V_fu_875_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_sinGen_my_to_float_31_1_s_fu_228_ap_done.read()))) {
        resultf_reg_1213 = grp_sinGen_my_to_float_31_1_s_fu_228_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tmp_5_reg_1178 = p_Val2_5_fu_979_p2.read().range(39, 16);
        tmp_7_reg_1183 = p_Val2_6_fu_986_p2.read().range(31, 16);
    }
}

void sinGen_sinf_or_cosf::thread_Ex_V_fu_467_p2() {
    Ex_V_fu_467_p2 = (!storemerge_i_fu_392_p3.read().is_01() || !tmp_31_i_fu_463_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(storemerge_i_fu_392_p3.read()) - sc_biguint<8>(tmp_31_i_fu_463_p1.read()));
}

void sinGen_sinf_or_cosf::thread_Mx_zeros_V_fu_432_p1() {
    Mx_zeros_V_fu_432_p1 = val_assign_fu_424_p3.read().range(5-1, 0);
}

void sinGen_sinf_or_cosf::thread_OP1_V_3_fu_803_p1() {
    OP1_V_3_fu_803_p1 = esl_zext<18,9>(tmp_1_reg_1113.read());
}

void sinGen_sinf_or_cosf::thread_addr_V_fu_272_p3() {
    addr_V_fu_272_p3 = (!closepath_fu_260_p2.read()[0].is_01())? sc_lv<8>(): ((closepath_fu_260_p2.read()[0].to_bool())? ap_const_lv8_3F: p_op_i_fu_266_p2.read());
}

void sinGen_sinf_or_cosf::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_return() {
    ap_return = (!tmp_16_fu_967_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_16_fu_967_p2.read()[0].to_bool())? sel_tmp4_fu_960_p3.read(): sel_tmp2_fu_956_p1.read());
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_123() {
    ap_sig_bdd_123 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_142() {
    ap_sig_bdd_142 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_180() {
    ap_sig_bdd_180 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_192() {
    ap_sig_bdd_192 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_203() {
    ap_sig_bdd_203 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_212() {
    ap_sig_bdd_212 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_223() {
    ap_sig_bdd_223 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_234() {
    ap_sig_bdd_234 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_35() {
    ap_sig_bdd_35 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_587() {
    ap_sig_bdd_587 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void sinGen_sinf_or_cosf::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_212.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_223.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_234.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_587.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_35.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_93.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_106.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_123.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_142.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_180.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_192.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_203.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_closepath_fu_260_p2() {
    closepath_fu_260_p2 = (!loc_V_fu_246_p4.read().is_01() || !ap_const_lv8_7E.is_01())? sc_lv<1>(): (sc_biguint<8>(loc_V_fu_246_p4.read()) < sc_biguint<8>(ap_const_lv8_7E));
}

void sinGen_sinf_or_cosf::thread_cos_basis_fu_654_p0() {
    cos_basis_fu_654_p0 =  (sc_lv<1>) (do_cos.read());
}

void sinGen_sinf_or_cosf::thread_cos_basis_fu_654_p3() {
    cos_basis_fu_654_p3 = (!cos_basis_fu_654_p0.read()[0].is_01())? sc_lv<1>(): ((cos_basis_fu_654_p0.read()[0].to_bool())? tmp_4_fu_619_p2.read(): tmp_s_fu_625_p10.read());
}

void sinGen_sinf_or_cosf::thread_grp_fu_887_ce() {
    grp_fu_887_ce = ap_const_logic_1;
}

void sinGen_sinf_or_cosf::thread_grp_fu_887_p1() {
    grp_fu_887_p1 =  (sc_lv<31>) (grp_fu_887_p10.read());
}

void sinGen_sinf_or_cosf::thread_grp_fu_887_p10() {
    grp_fu_887_p10 = esl_zext<62,31>(p_Mx_V_ret_reg_1123.read());
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V() {
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_a_V = Med_V_reg_1033.read();
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start() {
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start = grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_start_ap_start_reg.read();
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V() {
    grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_b_V = p_Result_13_reg_1028.read();
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_my_to_float_31_1_s_fu_228_ap_start() {
    grp_sinGen_my_to_float_31_1_s_fu_228_ap_start = grp_sinGen_my_to_float_31_1_s_fu_228_ap_start_ap_start_reg.read();
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_my_to_float_31_1_s_fu_228_in_V() {
    grp_sinGen_my_to_float_31_1_s_fu_228_in_V = p_0_reg_1203.read();
}

void sinGen_sinf_or_cosf::thread_grp_sinGen_my_to_float_31_1_s_fu_228_prescale() {
    grp_sinGen_my_to_float_31_1_s_fu_228_prescale = r_V_1_reg_1208.read();
}

void sinGen_sinf_or_cosf::thread_hls_ref_4oPi_table_100_V_address0() {
    hls_ref_4oPi_table_100_V_address0 =  (sc_lv<4>) (tmp_5_i_i_fu_290_p1.read());
}

void sinGen_sinf_or_cosf::thread_hls_ref_4oPi_table_100_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        hls_ref_4oPi_table_100_V_ce0 = ap_const_logic_1;
    } else {
        hls_ref_4oPi_table_100_V_ce0 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K0_V_address0() {
    hls_sin_cos_K0_V_address0 =  (sc_lv<8>) (tmp_8_fu_696_p1.read());
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        hls_sin_cos_K0_V_ce0 = ap_const_logic_1;
    } else {
        hls_sin_cos_K0_V_ce0 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K1_V_address0() {
    hls_sin_cos_K1_V_address0 =  (sc_lv<8>) (tmp_8_fu_696_p1.read());
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        hls_sin_cos_K1_V_ce0 = ap_const_logic_1;
    } else {
        hls_sin_cos_K1_V_ce0 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K2_V_address0() {
    hls_sin_cos_K2_V_address0 =  (sc_lv<8>) (tmp_8_fu_696_p1.read());
}

void sinGen_sinf_or_cosf::thread_hls_sin_cos_K2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        hls_sin_cos_K2_V_ce0 = ap_const_logic_1;
    } else {
        hls_sin_cos_K2_V_ce0 = ap_const_logic_0;
    }
}

void sinGen_sinf_or_cosf::thread_loc_V_1_fu_256_p1() {
    loc_V_1_fu_256_p1 = p_Val2_28_fu_234_p1.read().range(23-1, 0);
}

void sinGen_sinf_or_cosf::thread_loc_V_fu_246_p4() {
    loc_V_fu_246_p4 = p_Val2_28_fu_234_p1.read().range(30, 23);
}

void sinGen_sinf_or_cosf::thread_not_do_cos_fu_662_p0() {
    not_do_cos_fu_662_p0 =  (sc_lv<1>) (do_cos.read());
}

void sinGen_sinf_or_cosf::thread_not_do_cos_fu_662_p2() {
    not_do_cos_fu_662_p2 = (not_do_cos_fu_662_p0.read() ^ ap_const_lv1_1);
}

void sinGen_sinf_or_cosf::thread_or_cond_fu_486_p2() {
    or_cond_fu_486_p2 = (tmp_14_fu_481_p2.read() & tmp_15_reg_1038.read());
}

void sinGen_sinf_or_cosf::thread_p_Ex_V_ret_fu_682_p3() {
    p_Ex_V_ret_fu_682_p3 = (!cos_basis_fu_654_p3.read()[0].is_01())? sc_lv<8>(): ((cos_basis_fu_654_p3.read()[0].to_bool())? ap_const_lv8_0: Ex_V_reg_1071.read());
}

void sinGen_sinf_or_cosf::thread_p_Mx_V_ret_fu_689_p3() {
    p_Mx_V_ret_fu_689_p3 = (!cos_basis_fu_654_p3.read()[0].is_01())? sc_lv<31>(): ((cos_basis_fu_654_p3.read()[0].to_bool())? ap_const_lv31_7FFFFFFF: p_Val2_32_reg_1095.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_12_fu_925_p2() {
    p_Result_12_fu_925_p2 = (tmp_13_reg_1143.read() | p_Result_18_fu_917_p3.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_13_fu_299_p3() {
    p_Result_13_fu_299_p3 = esl_concat<1,23>(ap_const_lv1_1, loc_V_1_reg_1006.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_14_fu_399_p3() {
    p_Result_14_fu_399_p3 = esl_concat<18,1>(p_Result_i2_i_reg_1056.read(), ap_const_lv1_1);
}

void sinGen_sinf_or_cosf::thread_p_Result_15_fu_406_p4() {
    p_Result_15_fu_406_p4 = p_Result_14_fu_399_p3.read().range(0, 18);
}

void sinGen_sinf_or_cosf::thread_p_Result_16_fu_416_p3() {
    p_Result_16_fu_416_p3 = esl_concat<13,19>(ap_const_lv13_1FFF, p_Result_15_fu_406_p4.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_17_fu_674_p3() {
    p_Result_17_fu_674_p3 = esl_concat<1,7>(sin_basis_fu_668_p2.read(), p_Result_s_40_fu_568_p4.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_18_fu_917_p3() {
    p_Result_18_fu_917_p3 = p_Val2_25_fu_914_p1.read().range(31, 31);
}

void sinGen_sinf_or_cosf::thread_p_Result_19_fu_703_p3() {
    p_Result_19_fu_703_p3 = esl_concat<1,3>(p_Result_s_reg_993.read(), p_Val2_31_reg_1044.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_20_fu_930_p3() {
    p_Result_20_fu_930_p3 = esl_concat<1,31>(p_Result_s_reg_993.read(), ap_const_lv31_0);
}

void sinGen_sinf_or_cosf::thread_p_Result_21_fu_941_p3() {
    p_Result_21_fu_941_p3 = esl_concat<1,31>(p_Result_12_fu_925_p2.read(), tmp_25_fu_937_p1.read());
}

void sinGen_sinf_or_cosf::thread_p_Result_s_40_fu_568_p4() {
    p_Result_s_40_fu_568_p4 = p_Val2_0_i245_in_i_fu_561_p3.read().range(30, 24);
}

void sinGen_sinf_or_cosf::thread_p_Val2_0_i245_in_i_fu_561_p3() {
    p_Val2_0_i245_in_i_fu_561_p3 = (!isNeg_reg_1077.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_1077.read()[0].to_bool())? tmp_35_i_cast_fu_551_p1.read(): tmp_37_i_fu_555_p2.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_14_fu_332_p4() {
    p_Val2_14_fu_332_p4 = grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return.read().range(67, 19);
}

void sinGen_sinf_or_cosf::thread_p_Val2_19_fu_369_p3() {
    p_Val2_19_fu_369_p3 = (!tmp_20_fu_359_p1.read()[0].is_01())? sc_lv<49>(): ((tmp_20_fu_359_p1.read()[0].to_bool())? p_Val2_i_fu_363_p2.read(): p_Val2_14_fu_332_p4.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_22_fu_440_p2() {
    p_Val2_22_fu_440_p2 = (!tmp_28_i_fu_436_p1.read().is_01())? sc_lv<49>(): p_Val2_19_reg_1051.read() << (unsigned short)tmp_28_i_fu_436_p1.read().to_uint();
}

void sinGen_sinf_or_cosf::thread_p_Val2_25_fu_914_p1() {
    p_Val2_25_fu_914_p1 = resultf_reg_1213.read();
}

void sinGen_sinf_or_cosf::thread_p_Val2_28_fu_234_p1() {
    p_Val2_28_fu_234_p1 = t_in.read();
}

void sinGen_sinf_or_cosf::thread_p_Val2_31_fu_352_p3() {
    p_Val2_31_fu_352_p3 = (!closepath_reg_1012.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1012.read()[0].to_bool())? ap_const_lv3_0: tmp_27_i_fu_342_p4.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_32_fu_516_p2() {
    p_Val2_32_fu_516_p2 = (!p_Val2_23_reg_1061.read().is_01() || !tmp_30_i_fu_513_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(p_Val2_23_reg_1061.read()) + sc_biguint<31>(tmp_30_i_fu_513_p1.read()));
}

void sinGen_sinf_or_cosf::thread_p_Val2_3_fu_806_p0() {
    p_Val2_3_fu_806_p0 =  (sc_lv<9>) (OP1_V_3_fu_803_p1.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_3_fu_806_p1() {
    p_Val2_3_fu_806_p1 =  (sc_lv<9>) (OP1_V_3_fu_803_p1.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_3_fu_806_p2() {
    p_Val2_3_fu_806_p2 = (!p_Val2_3_fu_806_p0.read().is_01() || !p_Val2_3_fu_806_p1.read().is_01())? sc_lv<18>(): sc_biguint<9>(p_Val2_3_fu_806_p0.read()) * sc_biguint<9>(p_Val2_3_fu_806_p1.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_5_fu_979_p1() {
    p_Val2_5_fu_979_p1 =  (sc_lv<17>) (p_Val2_5_fu_979_p10.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_5_fu_979_p10() {
    p_Val2_5_fu_979_p10 = esl_zext<40,17>(p_Val2_2_reg_1108.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_6_fu_986_p0() {
    p_Val2_6_fu_986_p0 =  (sc_lv<17>) (p_Val2_6_fu_986_p00.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_6_fu_986_p00() {
    p_Val2_6_fu_986_p00 = esl_zext<32,17>(tmp_3_reg_1158.read());
}

void sinGen_sinf_or_cosf::thread_p_Val2_7_fu_852_p3() {
    p_Val2_7_fu_852_p3 = esl_concat<30,1>(p_Val2_s_reg_1163.read(), ap_const_lv1_0);
}

void sinGen_sinf_or_cosf::thread_p_Val2_8_fu_866_p2() {
    p_Val2_8_fu_866_p2 = (!tmp_9_fu_859_p1.read().is_01() || !tmp_10_fu_863_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_9_fu_859_p1.read()) + sc_bigint<32>(tmp_10_fu_863_p1.read()));
}

void sinGen_sinf_or_cosf::thread_p_Val2_i_fu_363_p2() {
    p_Val2_i_fu_363_p2 = (!ap_const_lv49_0.is_01() || !p_Val2_14_fu_332_p4.read().is_01())? sc_lv<49>(): (sc_biguint<49>(ap_const_lv49_0) - sc_biguint<49>(p_Val2_14_fu_332_p4.read()));
}

void sinGen_sinf_or_cosf::thread_p_i_fu_387_p2() {
    p_i_fu_387_p2 = (!ap_const_lv8_83.is_01() || !loc_V_reg_999.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_83) + sc_biguint<8>(loc_V_reg_999.read()));
}

void sinGen_sinf_or_cosf::thread_p_op_i_fu_266_p2() {
    p_op_i_fu_266_p2 = (!ap_const_lv8_C2.is_01() || !loc_V_fu_246_p4.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_C2) + sc_biguint<8>(loc_V_fu_246_p4.read()));
}

void sinGen_sinf_or_cosf::thread_r_V_1_fu_907_p2() {
    r_V_1_fu_907_p2 = (!ap_const_lv9_0.is_01() || !rhs_V_fu_904_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(rhs_V_fu_904_p1.read()));
}

void sinGen_sinf_or_cosf::thread_r_V_3_fu_310_p2() {
    r_V_3_fu_310_p2 = (!tmp_7_i_i_fu_307_p1.read().is_01())? sc_lv<100>(): hls_ref_4oPi_table_100_V_q0.read() << (unsigned short)tmp_7_i_i_fu_307_p1.read().to_uint();
}

void sinGen_sinf_or_cosf::thread_r_V_fu_875_p2() {
    r_V_fu_875_p2 = (!p_Val2_8_fu_866_p2.read().is_01() || !tmp_18_cast_fu_872_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_Val2_8_fu_866_p2.read()) + sc_bigint<32>(tmp_18_cast_fu_872_p1.read()));
}

void sinGen_sinf_or_cosf::thread_rhs_V_fu_904_p1() {
    rhs_V_fu_904_p1 = esl_sext<9,8>(p_Ex_V_ret_reg_1118.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp1_fu_793_p2() {
    sel_tmp1_fu_793_p2 = (or_cond_reg_1083.read() & not_do_cos_fu_662_p2.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp2_fu_956_p1() {
    sel_tmp2_fu_956_p1 = sel_tmp2_v_fu_949_p3.read();
}

void sinGen_sinf_or_cosf::thread_sel_tmp2_v_fu_949_p3() {
    sel_tmp2_v_fu_949_p3 = (!sel_tmp1_reg_1148.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_reg_1148.read()[0].to_bool())? p_Result_20_fu_930_p3.read(): p_Result_21_fu_941_p3.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp3_fu_798_p1() {
    sel_tmp3_fu_798_p1 =  (sc_lv<1>) (do_cos.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp3_fu_798_p2() {
    sel_tmp3_fu_798_p2 = (or_cond_reg_1083.read() & sel_tmp3_fu_798_p1.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp4_fu_960_p3() {
    sel_tmp4_fu_960_p3 = (!sel_tmp6_reg_1089.read()[0].is_01())? sc_lv<32>(): ((sel_tmp6_reg_1089.read()[0].to_bool())? ap_const_lv32_7FFFFFFF: ap_const_lv32_3F800000);
}

void sinGen_sinf_or_cosf::thread_sel_tmp5_demorgan_fu_496_p2() {
    sel_tmp5_demorgan_fu_496_p2 = (tmp_14_fu_481_p2.read() & tmp_15_reg_1038.read());
}

void sinGen_sinf_or_cosf::thread_sel_tmp5_fu_501_p2() {
    sel_tmp5_fu_501_p2 = (sel_tmp5_demorgan_fu_496_p2.read() ^ ap_const_lv1_1);
}

void sinGen_sinf_or_cosf::thread_sel_tmp6_fu_507_p2() {
    sel_tmp6_fu_507_p2 = (tmp_i_fu_491_p2.read() & sel_tmp5_fu_501_p2.read());
}

void sinGen_sinf_or_cosf::thread_sh_assign_1_i_cast8_fu_537_p1() {
    sh_assign_1_i_cast8_fu_537_p1 = esl_sext<32,9>(sh_assign_reg_1102.read());
}

void sinGen_sinf_or_cosf::thread_sh_assign_1_i_cast_fu_540_p1() {
    sh_assign_1_i_cast_fu_540_p1 = esl_sext<31,9>(sh_assign_reg_1102.read());
}

void sinGen_sinf_or_cosf::thread_sh_assign_fu_530_p3() {
    sh_assign_fu_530_p3 = (!isNeg_reg_1077.read()[0].is_01())? sc_lv<9>(): ((isNeg_reg_1077.read()[0].to_bool())? tmp_33_i_fu_524_p2.read(): sh_i_cast_fu_521_p1.read());
}

void sinGen_sinf_or_cosf::thread_sh_i_cast_fu_521_p1() {
    sh_i_cast_fu_521_p1 = esl_sext<9,8>(Ex_V_reg_1071.read());
}

void sinGen_sinf_or_cosf::thread_sin_basis_fu_668_p2() {
    sin_basis_fu_668_p2 = (tmp_6_fu_646_p3.read() ^ not_do_cos_fu_662_p2.read());
}

void sinGen_sinf_or_cosf::thread_storemerge_i_fu_392_p3() {
    storemerge_i_fu_392_p3 = (!closepath_reg_1012.read()[0].is_01())? sc_lv<8>(): ((closepath_reg_1012.read()[0].to_bool())? p_i_fu_387_p2.read(): ap_const_lv8_0);
}

void sinGen_sinf_or_cosf::thread_tmp_10_fu_863_p1() {
    tmp_10_fu_863_p1 = esl_sext<32,24>(tmp_5_reg_1178.read());
}

void sinGen_sinf_or_cosf::thread_tmp_13_fu_785_p3() {
    tmp_13_fu_785_p3 = (!cos_basis_fu_654_p3.read()[0].is_01())? sc_lv<1>(): ((cos_basis_fu_654_p3.read()[0].to_bool())? tmp_11_fu_709_p18.read(): tmp_12_fu_747_p18.read());
}

void sinGen_sinf_or_cosf::thread_tmp_14_fu_481_p2() {
    tmp_14_fu_481_p2 = (!loc_V_reg_999.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_999.read() == ap_const_lv8_0);
}

void sinGen_sinf_or_cosf::thread_tmp_15_fu_327_p2() {
    tmp_15_fu_327_p2 = (!loc_V_1_reg_1006.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_reg_1006.read() == ap_const_lv23_0);
}

void sinGen_sinf_or_cosf::thread_tmp_16_fu_967_p2() {
    tmp_16_fu_967_p2 = (sel_tmp6_reg_1089.read() | sel_tmp3_reg_1153.read());
}

void sinGen_sinf_or_cosf::thread_tmp_18_cast_fu_872_p1() {
    tmp_18_cast_fu_872_p1 = esl_sext<32,16>(tmp_7_reg_1183.read());
}

void sinGen_sinf_or_cosf::thread_tmp_19_fu_295_p1() {
    tmp_19_fu_295_p1 = addr_V_fu_272_p3.read().range(4-1, 0);
}

void sinGen_sinf_or_cosf::thread_tmp_20_fu_359_p1() {
    tmp_20_fu_359_p1 = p_Val2_31_fu_352_p3.read().range(1-1, 0);
}

void sinGen_sinf_or_cosf::thread_tmp_25_fu_937_p1() {
    tmp_25_fu_937_p1 = p_Val2_25_fu_914_p1.read().range(31-1, 0);
}

void sinGen_sinf_or_cosf::thread_tmp_27_i_fu_342_p4() {
    tmp_27_i_fu_342_p4 = grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_return.read().range(70, 68);
}

void sinGen_sinf_or_cosf::thread_tmp_28_i_fu_436_p1() {
    tmp_28_i_fu_436_p1 = esl_zext<49,5>(Mx_zeros_V_fu_432_p1.read());
}

void sinGen_sinf_or_cosf::thread_tmp_2_fu_280_p4() {
    tmp_2_fu_280_p4 = addr_V_fu_272_p3.read().range(7, 4);
}

void sinGen_sinf_or_cosf::thread_tmp_30_i_fu_513_p1() {
    tmp_30_i_fu_513_p1 = esl_zext<31,1>(tmp_22_reg_1066.read());
}

void sinGen_sinf_or_cosf::thread_tmp_31_i_fu_463_p1() {
    tmp_31_i_fu_463_p1 = esl_zext<8,5>(Mx_zeros_V_fu_432_p1.read());
}

void sinGen_sinf_or_cosf::thread_tmp_33_i_fu_524_p2() {
    tmp_33_i_fu_524_p2 = (!ap_const_lv9_0.is_01() || !sh_i_cast_fu_521_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(sh_i_cast_fu_521_p1.read()));
}

void sinGen_sinf_or_cosf::thread_tmp_34_i_fu_543_p1() {
    tmp_34_i_fu_543_p1 = esl_zext<32,31>(p_Val2_32_reg_1095.read());
}

void sinGen_sinf_or_cosf::thread_tmp_35_i_cast_fu_551_p1() {
    tmp_35_i_cast_fu_551_p1 = esl_zext<32,31>(tmp_35_i_fu_546_p2.read());
}

void sinGen_sinf_or_cosf::thread_tmp_35_i_fu_546_p2() {
    tmp_35_i_fu_546_p2 = (!sh_assign_1_i_cast_fu_540_p1.read().is_01())? sc_lv<31>(): p_Val2_32_reg_1095.read() >> (unsigned short)sh_assign_1_i_cast_fu_540_p1.read().to_uint();
}

void sinGen_sinf_or_cosf::thread_tmp_37_i_fu_555_p2() {
    tmp_37_i_fu_555_p2 = (!sh_assign_1_i_cast8_fu_537_p1.read().is_01())? sc_lv<32>(): tmp_34_i_fu_543_p1.read() << (unsigned short)sh_assign_1_i_cast8_fu_537_p1.read().to_uint();
}

void sinGen_sinf_or_cosf::thread_tmp_4_fu_619_p2() {
    tmp_4_fu_619_p2 = (tmp_fu_598_p10.read() ^ ap_const_lv1_1);
}

void sinGen_sinf_or_cosf::thread_tmp_5_i_i_fu_290_p1() {
    tmp_5_i_i_fu_290_p1 = esl_zext<64,4>(tmp_2_fu_280_p4.read());
}

void sinGen_sinf_or_cosf::thread_tmp_6_fu_646_p0() {
    tmp_6_fu_646_p0 =  (sc_lv<1>) (do_cos.read());
}

void sinGen_sinf_or_cosf::thread_tmp_6_fu_646_p3() {
    tmp_6_fu_646_p3 = (!tmp_6_fu_646_p0.read()[0].is_01())? sc_lv<1>(): ((tmp_6_fu_646_p0.read()[0].to_bool())? tmp_fu_598_p10.read(): tmp_s_fu_625_p10.read());
}

void sinGen_sinf_or_cosf::thread_tmp_7_i_i_fu_307_p1() {
    tmp_7_i_i_fu_307_p1 = esl_zext<100,4>(tmp_19_reg_1023.read());
}

void sinGen_sinf_or_cosf::thread_tmp_8_fu_696_p1() {
    tmp_8_fu_696_p1 = esl_zext<64,8>(p_Result_17_fu_674_p3.read());
}

void sinGen_sinf_or_cosf::thread_tmp_9_fu_859_p1() {
    tmp_9_fu_859_p1 = esl_sext<32,31>(p_Val2_7_fu_852_p3.read());
}

void sinGen_sinf_or_cosf::thread_tmp_i_fu_491_p2() {
    tmp_i_fu_491_p2 = (!loc_V_reg_999.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_999.read() == ap_const_lv8_FF);
}

void sinGen_sinf_or_cosf::thread_val_assign_fu_424_p3() {
    val_assign_fu_424_p3 = esl_cttz<32,32>(p_Result_16_fu_416_p3.read());
}

void sinGen_sinf_or_cosf::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_sinGen_big_mult_v3small_71_24_17_s_fu_222_ap_done.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_sinGen_my_to_float_31_1_s_fu_228_ap_done.read())) {
                ap_NS_fsm = ap_ST_st17_fsm_16;
            } else {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXX";
            break;
    }
}

}

