// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstepgen.h"

extern XStepgen_Config XStepgen_ConfigTable[];

XStepgen_Config *XStepgen_LookupConfig(u16 DeviceId) {
	XStepgen_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTEPGEN_NUM_INSTANCES; Index++) {
		if (XStepgen_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStepgen_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStepgen_Initialize(XStepgen *InstancePtr, u16 DeviceId) {
	XStepgen_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStepgen_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStepgen_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

