// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsingen.h"

extern XSingen_Config XSingen_ConfigTable[];

XSingen_Config *XSingen_LookupConfig(u16 DeviceId) {
	XSingen_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSINGEN_NUM_INSTANCES; Index++) {
		if (XSingen_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSingen_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSingen_Initialize(XSingen *InstancePtr, u16 DeviceId) {
	XSingen_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSingen_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSingen_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

