// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsingenerator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSingenerator_CfgInitialize(XSingenerator *InstancePtr, XSingenerator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSingenerator_Start(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSingenerator_IsDone(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSingenerator_IsIdle(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSingenerator_IsReady(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSingenerator_EnableAutoRestart(XSingenerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSingenerator_DisableAutoRestart(XSingenerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XSingenerator_Set_pi(XSingenerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_PI_DATA, Data);
}

u32 XSingenerator_Get_pi(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_PI_DATA);
    return Data;
}

void XSingenerator_Set_w(XSingenerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_W_DATA, Data);
}

u32 XSingenerator_Get_w(XSingenerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_W_DATA);
    return Data;
}

void XSingenerator_InterruptGlobalEnable(XSingenerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_GIE, 1);
}

void XSingenerator_InterruptGlobalDisable(XSingenerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_GIE, 0);
}

void XSingenerator_InterruptEnable(XSingenerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_IER);
    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XSingenerator_InterruptDisable(XSingenerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_IER);
    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XSingenerator_InterruptClear(XSingenerator *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingenerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XSingenerator_InterruptGetEnabled(XSingenerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_IER);
}

u32 XSingenerator_InterruptGetStatus(XSingenerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSingenerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSINGENERATOR_CRTL_BUS_ADDR_ISR);
}

