// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsingenerator.h"

extern XSingenerator_Config XSingenerator_ConfigTable[];

XSingenerator_Config *XSingenerator_LookupConfig(u16 DeviceId) {
	XSingenerator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSINGENERATOR_NUM_INSTANCES; Index++) {
		if (XSingenerator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSingenerator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSingenerator_Initialize(XSingenerator *InstancePtr, u16 DeviceId) {
	XSingenerator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSingenerator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSingenerator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

