webtalk_init -webtalk_dir E:\\ZedBoard_Projects\\FcommesSalar\\zed\\fmcomms1_zed.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 16 20:01:19 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bmgtg53b4t70i8sr85769u28bo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1531737718849" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1531737718849"
webtalk_add_data -client sdk -key uid -value "1531737740356" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1531737740356"
webtalk_add_data -client sdk -key uid -value "1531737755241" -context "sdk\\\\bsp/1531737755241"
webtalk_add_data -client sdk -key hwid -value "1531737740356" -context "sdk\\\\bsp/1531737755241"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1531737755241"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1531737755241"
webtalk_add_data -client sdk -key uid -value "1531737757367" -context "sdk\\\\application/1531737757367"
webtalk_add_data -client sdk -key hwid -value "1531737740356" -context "sdk\\\\application/1531737757367"
webtalk_add_data -client sdk -key bspid -value "1531737755241" -context "sdk\\\\application/1531737757367"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1531737757367"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1531737757367"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1531737757367"
webtalk_transmit -clientid 3884981604 -regid "" -xml E:\\ZedBoard_Projects\\FcommesSalar\\zed\\fmcomms1_zed.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\ZedBoard_Projects\\FcommesSalar\\zed\\fmcomms1_zed.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\ZedBoard_Projects\\FcommesSalar\\zed\\fmcomms1_zed.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
