// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsingen.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSingen_CfgInitialize(XSingen *InstancePtr, XSingen_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtls_BaseAddress = ConfigPtr->Crtls_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSingen_Start(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL) & 0x80;
    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSingen_IsDone(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSingen_IsIdle(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSingen_IsReady(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSingen_EnableAutoRestart(XSingen *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL, 0x80);
}

void XSingen_DisableAutoRestart(XSingen *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AP_CTRL, 0);
}

void XSingen_Set_Fs(XSingen *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_FS_DATA, Data);
}

u32 XSingen_Get_Fs(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_FS_DATA);
    return Data;
}

void XSingen_Set_cycle(XSingen *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_CYCLE_DATA, Data);
}

u32 XSingen_Get_cycle(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_CYCLE_DATA);
    return Data;
}

void XSingen_Set_amp(XSingen *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AMP_DATA, Data);
}

u32 XSingen_Get_amp(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_AMP_DATA);
    return Data;
}

void XSingen_Set_binOffset(XSingen *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_BINOFFSET_DATA, Data);
}

u32 XSingen_Get_binOffset(XSingen *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_BINOFFSET_DATA);
    return Data;
}

u32 XSingen_Get_outIQ_BaseAddress(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_BASE);
}

u32 XSingen_Get_outIQ_HighAddress(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_HIGH);
}

u32 XSingen_Get_outIQ_TotalBytes(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XSINGEN_CRTLS_ADDR_OUTIQ_HIGH - XSINGEN_CRTLS_ADDR_OUTIQ_BASE + 1);
}

u32 XSingen_Get_outIQ_BitWidth(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSINGEN_CRTLS_WIDTH_OUTIQ;
}

u32 XSingen_Get_outIQ_Depth(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSINGEN_CRTLS_DEPTH_OUTIQ;
}

u32 XSingen_Write_outIQ_Words(XSingen *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSINGEN_CRTLS_ADDR_OUTIQ_HIGH - XSINGEN_CRTLS_ADDR_OUTIQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XSingen_Read_outIQ_Words(XSingen *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSINGEN_CRTLS_ADDR_OUTIQ_HIGH - XSINGEN_CRTLS_ADDR_OUTIQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_BASE + (offset + i)*4);
    }
    return length;
}

u32 XSingen_Write_outIQ_Bytes(XSingen *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSINGEN_CRTLS_ADDR_OUTIQ_HIGH - XSINGEN_CRTLS_ADDR_OUTIQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XSingen_Read_outIQ_Bytes(XSingen *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSINGEN_CRTLS_ADDR_OUTIQ_HIGH - XSINGEN_CRTLS_ADDR_OUTIQ_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Crtls_BaseAddress + XSINGEN_CRTLS_ADDR_OUTIQ_BASE + offset + i);
    }
    return length;
}

void XSingen_InterruptGlobalEnable(XSingen *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_GIE, 1);
}

void XSingen_InterruptGlobalDisable(XSingen *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_GIE, 0);
}

void XSingen_InterruptEnable(XSingen *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_IER);
    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_IER, Register | Mask);
}

void XSingen_InterruptDisable(XSingen *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_IER);
    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_IER, Register & (~Mask));
}

void XSingen_InterruptClear(XSingen *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSingen_WriteReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_ISR, Mask);
}

u32 XSingen_InterruptGetEnabled(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_IER);
}

u32 XSingen_InterruptGetStatus(XSingen *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSingen_ReadReg(InstancePtr->Crtls_BaseAddress, XSINGEN_CRTLS_ADDR_ISR);
}

