// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sinGen,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=17177,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=41,HLS_SYN_FF=8806,HLS_SYN_LUT=19263}" *)

module sinGen (
        ap_clk,
        ap_rst_n,
        s_axi_CRTLS_AWVALID,
        s_axi_CRTLS_AWREADY,
        s_axi_CRTLS_AWADDR,
        s_axi_CRTLS_WVALID,
        s_axi_CRTLS_WREADY,
        s_axi_CRTLS_WDATA,
        s_axi_CRTLS_WSTRB,
        s_axi_CRTLS_ARVALID,
        s_axi_CRTLS_ARREADY,
        s_axi_CRTLS_ARADDR,
        s_axi_CRTLS_RVALID,
        s_axi_CRTLS_RREADY,
        s_axi_CRTLS_RDATA,
        s_axi_CRTLS_RRESP,
        s_axi_CRTLS_BVALID,
        s_axi_CRTLS_BREADY,
        s_axi_CRTLS_BRESP,
        interrupt
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 72'b1;
parameter    ap_ST_st2_fsm_1 = 72'b10;
parameter    ap_ST_st3_fsm_2 = 72'b100;
parameter    ap_ST_st4_fsm_3 = 72'b1000;
parameter    ap_ST_st5_fsm_4 = 72'b10000;
parameter    ap_ST_st6_fsm_5 = 72'b100000;
parameter    ap_ST_st7_fsm_6 = 72'b1000000;
parameter    ap_ST_st8_fsm_7 = 72'b10000000;
parameter    ap_ST_st9_fsm_8 = 72'b100000000;
parameter    ap_ST_st10_fsm_9 = 72'b1000000000;
parameter    ap_ST_st11_fsm_10 = 72'b10000000000;
parameter    ap_ST_st12_fsm_11 = 72'b100000000000;
parameter    ap_ST_st13_fsm_12 = 72'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 72'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 72'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 72'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 72'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 72'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 72'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 72'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 72'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 72'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 72'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 72'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 72'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 72'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 72'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 72'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 72'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 72'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 72'b1000000000000000000000000000000;
parameter    ap_ST_st32_fsm_31 = 72'b10000000000000000000000000000000;
parameter    ap_ST_st33_fsm_32 = 72'b100000000000000000000000000000000;
parameter    ap_ST_st34_fsm_33 = 72'b1000000000000000000000000000000000;
parameter    ap_ST_st35_fsm_34 = 72'b10000000000000000000000000000000000;
parameter    ap_ST_st36_fsm_35 = 72'b100000000000000000000000000000000000;
parameter    ap_ST_st37_fsm_36 = 72'b1000000000000000000000000000000000000;
parameter    ap_ST_st38_fsm_37 = 72'b10000000000000000000000000000000000000;
parameter    ap_ST_st39_fsm_38 = 72'b100000000000000000000000000000000000000;
parameter    ap_ST_st40_fsm_39 = 72'b1000000000000000000000000000000000000000;
parameter    ap_ST_st41_fsm_40 = 72'b10000000000000000000000000000000000000000;
parameter    ap_ST_st42_fsm_41 = 72'b100000000000000000000000000000000000000000;
parameter    ap_ST_st43_fsm_42 = 72'b1000000000000000000000000000000000000000000;
parameter    ap_ST_st44_fsm_43 = 72'b10000000000000000000000000000000000000000000;
parameter    ap_ST_st45_fsm_44 = 72'b100000000000000000000000000000000000000000000;
parameter    ap_ST_st46_fsm_45 = 72'b1000000000000000000000000000000000000000000000;
parameter    ap_ST_st47_fsm_46 = 72'b10000000000000000000000000000000000000000000000;
parameter    ap_ST_st48_fsm_47 = 72'b100000000000000000000000000000000000000000000000;
parameter    ap_ST_st49_fsm_48 = 72'b1000000000000000000000000000000000000000000000000;
parameter    ap_ST_st50_fsm_49 = 72'b10000000000000000000000000000000000000000000000000;
parameter    ap_ST_st51_fsm_50 = 72'b100000000000000000000000000000000000000000000000000;
parameter    ap_ST_st52_fsm_51 = 72'b1000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st53_fsm_52 = 72'b10000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st54_fsm_53 = 72'b100000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st55_fsm_54 = 72'b1000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st56_fsm_55 = 72'b10000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st57_fsm_56 = 72'b100000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st58_fsm_57 = 72'b1000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st59_fsm_58 = 72'b10000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st60_fsm_59 = 72'b100000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st61_fsm_60 = 72'b1000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st62_fsm_61 = 72'b10000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st63_fsm_62 = 72'b100000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st64_fsm_63 = 72'b1000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st65_fsm_64 = 72'b10000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st66_fsm_65 = 72'b100000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st67_fsm_66 = 72'b1000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st68_fsm_67 = 72'b10000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st69_fsm_68 = 72'b100000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st70_fsm_69 = 72'b1000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st71_fsm_70 = 72'b10000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_ST_st72_fsm_71 = 72'b100000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    C_S_AXI_CRTLS_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_CRTLS_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_29 = 32'b101001;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_2B = 32'b101011;
parameter    ap_const_lv32_3B = 32'b111011;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_44 = 32'b1000100;
parameter    ap_const_lv32_45 = 32'b1000101;
parameter    ap_const_lv32_46 = 32'b1000110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_24 = 32'b100100;
parameter    ap_const_lv32_47 = 32'b1000111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_40800000 = 32'b1000000100000000000000000000000;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv64_40091EB851EB851F = 64'b100000000001001000111101011100001010001111010111000010100011111;
parameter    ap_const_lv64_3F80000000000000 = 64'b11111110000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv8_80 = 8'b10000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv9_181 = 9'b110000001;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv8_7F = 8'b1111111;
parameter    ap_const_lv32_36 = 32'b110110;
parameter    ap_const_lv32_25 = 32'b100101;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_true = 1'b1;
parameter    C_S_AXI_CRTLS_WSTRB_WIDTH = (C_S_AXI_CRTLS_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CRTLS_AWVALID;
output   s_axi_CRTLS_AWREADY;
input  [C_S_AXI_CRTLS_ADDR_WIDTH - 1 : 0] s_axi_CRTLS_AWADDR;
input   s_axi_CRTLS_WVALID;
output   s_axi_CRTLS_WREADY;
input  [C_S_AXI_CRTLS_DATA_WIDTH - 1 : 0] s_axi_CRTLS_WDATA;
input  [C_S_AXI_CRTLS_WSTRB_WIDTH - 1 : 0] s_axi_CRTLS_WSTRB;
input   s_axi_CRTLS_ARVALID;
output   s_axi_CRTLS_ARREADY;
input  [C_S_AXI_CRTLS_ADDR_WIDTH - 1 : 0] s_axi_CRTLS_ARADDR;
output   s_axi_CRTLS_RVALID;
input   s_axi_CRTLS_RREADY;
output  [C_S_AXI_CRTLS_DATA_WIDTH - 1 : 0] s_axi_CRTLS_RDATA;
output  [1:0] s_axi_CRTLS_RRESP;
output   s_axi_CRTLS_BVALID;
input   s_axi_CRTLS_BREADY;
output  [1:0] s_axi_CRTLS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [71:0] ap_CS_fsm = 72'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_90;
reg    ap_ready;
wire   [31:0] Fs;
wire   [31:0] cycle;
wire   [31:0] amp;
wire   [31:0] binOffset;
reg   [7:0] outIQ_address0;
reg    outIQ_ce0;
reg    outIQ_we0;
reg   [31:0] outIQ_d0;
wire    sinGen_CRTLS_s_axi_U_ap_dummy_ce;
wire   [63:0] grp_fu_283_p1;
reg   [63:0] reg_286;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_150;
reg    ap_sig_cseq_ST_st24_fsm_23;
reg    ap_sig_bdd_157;
wire   [63:0] grp_fu_277_p2;
reg   [63:0] reg_292;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_167;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_174;
reg   [31:0] binOffset_read_reg_602;
reg   [31:0] amp_read_reg_607;
wire   [63:0] cycle5_fu_297_p1;
wire   [31:0] idx_cast4_fu_302_p1;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_193;
wire   [7:0] idx_1_fu_313_p2;
reg   [7:0] idx_1_reg_625;
wire   [0:0] exitcond_fu_307_p2;
reg   [63:0] tmp_4_reg_640;
reg    ap_sig_cseq_ST_st30_fsm_29;
reg    ap_sig_bdd_212;
wire   [31:0] t_in_assign_fu_274_p1;
reg   [31:0] t_in_assign_reg_645;
reg    ap_sig_cseq_ST_st31_fsm_30;
reg    ap_sig_bdd_221;
wire   [31:0] grp_sinGen_sinf_or_cosf_fu_200_ap_return;
reg   [31:0] tmp_i_i_reg_651;
reg    ap_sig_cseq_ST_st33_fsm_32;
reg    ap_sig_bdd_230;
wire    grp_sinGen_sinf_or_cosf_fu_200_ap_done;
wire    grp_sinGen_sinf_or_cosf_fu_215_ap_done;
wire   [31:0] grp_sinGen_sinf_or_cosf_fu_215_ap_return;
reg   [31:0] tmp_i_i1_reg_656;
wire   [31:0] grp_sinGen_max_fu_230_ap_return;
reg   [31:0] maxI_reg_661;
reg    ap_sig_cseq_ST_st42_fsm_41;
reg    ap_sig_bdd_248;
wire    grp_sinGen_max_fu_230_ap_done;
wire    grp_sinGen_max_fu_235_ap_done;
wire   [31:0] grp_sinGen_max_fu_235_ap_return;
reg   [31:0] maxQ_reg_666;
wire   [31:0] grp_fu_268_p1;
reg   [31:0] tmp_i_reg_671;
wire   [31:0] grp_fu_271_p1;
reg   [31:0] tmp_i_41_reg_677;
wire   [7:0] i_fu_339_p2;
reg   [7:0] i_reg_686;
reg    ap_sig_cseq_ST_st43_fsm_42;
reg    ap_sig_bdd_270;
wire   [0:0] exitcond_i_fu_333_p2;
wire   [31:0] rawI_q0;
reg   [31:0] rawI_load_reg_701;
reg    ap_sig_cseq_ST_st44_fsm_43;
reg    ap_sig_bdd_286;
wire   [31:0] rawQ_q0;
reg   [31:0] rawQ_load_reg_706;
wire   [31:0] grp_fu_260_p2;
reg   [31:0] tmp_60_i_reg_711;
reg    ap_sig_cseq_ST_st60_fsm_59;
reg    ap_sig_bdd_297;
wire   [31:0] grp_fu_264_p2;
reg   [31:0] tmp_65_i_reg_716;
wire   [31:0] grp_fu_248_p2;
reg   [31:0] tmp_61_i_reg_721;
reg    ap_sig_cseq_ST_st64_fsm_63;
reg    ap_sig_bdd_308;
wire   [31:0] grp_fu_254_p2;
reg   [31:0] tmp_66_i_reg_726;
reg   [7:0] loc_V_reg_731;
reg    ap_sig_cseq_ST_st69_fsm_68;
reg    ap_sig_bdd_319;
wire   [22:0] loc_V_2_fu_365_p1;
reg   [22:0] loc_V_2_reg_737;
reg   [7:0] loc_V_3_reg_742;
wire   [22:0] loc_V_4_fu_383_p1;
reg   [22:0] loc_V_4_reg_748;
wire   [0:0] isNeg_fu_396_p3;
reg   [0:0] isNeg_reg_753;
reg    ap_sig_cseq_ST_st70_fsm_69;
reg    ap_sig_bdd_334;
wire   [8:0] sh_assign_1_fu_413_p3;
reg   [8:0] sh_assign_1_reg_758;
wire   [7:0] tmp_29_fu_484_p2;
reg   [7:0] tmp_29_reg_764;
reg    ap_sig_cseq_ST_st71_fsm_70;
reg    ap_sig_bdd_345;
wire   [0:0] isNeg_1_fu_504_p3;
reg   [0:0] isNeg_1_reg_769;
wire   [8:0] sh_assign_3_fu_521_p3;
reg   [8:0] sh_assign_3_reg_774;
reg   [6:0] rawI_address0;
reg    rawI_ce0;
reg    rawI_we0;
wire   [31:0] rawI_d0;
reg   [6:0] rawQ_address0;
reg    rawQ_ce0;
reg    rawQ_we0;
wire   [31:0] rawQ_d0;
wire    grp_sinGen_sinf_or_cosf_fu_200_ap_start;
wire    grp_sinGen_sinf_or_cosf_fu_200_ap_idle;
wire    grp_sinGen_sinf_or_cosf_fu_200_ap_ready;
wire   [31:0] grp_sinGen_sinf_or_cosf_fu_200_t_in;
wire    grp_sinGen_sinf_or_cosf_fu_200_do_cos;
wire    grp_sinGen_sinf_or_cosf_fu_215_ap_start;
wire    grp_sinGen_sinf_or_cosf_fu_215_ap_idle;
wire    grp_sinGen_sinf_or_cosf_fu_215_ap_ready;
wire   [31:0] grp_sinGen_sinf_or_cosf_fu_215_t_in;
wire    grp_sinGen_sinf_or_cosf_fu_215_do_cos;
wire    grp_sinGen_max_fu_230_ap_start;
wire    grp_sinGen_max_fu_230_ap_idle;
wire    grp_sinGen_max_fu_230_ap_ready;
wire   [6:0] grp_sinGen_max_fu_230_data_address0;
wire    grp_sinGen_max_fu_230_data_ce0;
wire   [31:0] grp_sinGen_max_fu_230_data_q0;
wire    grp_sinGen_max_fu_235_ap_start;
wire    grp_sinGen_max_fu_235_ap_idle;
wire    grp_sinGen_max_fu_235_ap_ready;
wire   [6:0] grp_sinGen_max_fu_235_data_address0;
wire    grp_sinGen_max_fu_235_data_ce0;
wire   [31:0] grp_sinGen_max_fu_235_data_q0;
reg   [7:0] idx_reg_176;
reg    ap_sig_cseq_ST_st37_fsm_36;
reg    ap_sig_bdd_404;
reg   [7:0] i_i_reg_188;
reg    ap_sig_cseq_ST_st72_fsm_71;
reg    ap_sig_bdd_413;
reg    grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st32_fsm_31;
reg    ap_sig_bdd_422;
reg    grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg = 1'b0;
reg    grp_sinGen_max_fu_230_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st41_fsm_40;
reg    ap_sig_bdd_477;
reg    grp_sinGen_max_fu_235_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_8_fu_327_p1;
wire   [63:0] tmp_59_i_fu_345_p1;
wire   [63:0] tmp_64_i_fu_490_p1;
wire   [63:0] tmp_69_i_fu_597_p1;
wire   [31:0] result_V_fu_476_p3;
wire   [31:0] result_V_1_fu_584_p3;
reg   [31:0] grp_fu_248_p0;
reg   [31:0] grp_fu_248_p1;
reg    ap_sig_cseq_ST_st34_fsm_33;
reg    ap_sig_bdd_514;
reg    ap_sig_cseq_ST_st61_fsm_60;
reg    ap_sig_bdd_521;
reg   [31:0] grp_fu_254_p0;
reg   [31:0] grp_fu_254_p1;
wire   [63:0] grp_fu_268_p0;
wire   [63:0] grp_fu_271_p0;
reg   [63:0] grp_fu_277_p0;
reg   [63:0] grp_fu_277_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_548;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_555;
reg    ap_sig_cseq_ST_st25_fsm_24;
reg    ap_sig_bdd_562;
reg   [63:0] grp_fu_283_p0;
wire   [31:0] grp_fu_240_p2;
wire   [31:0] p_Val2_s_fu_351_p1;
wire   [31:0] grp_fu_244_p2;
wire   [31:0] p_Val2_36_fu_369_p1;
wire   [8:0] tmp_i_i_i_i_cast2_fu_387_p1;
wire   [8:0] sh_assign_fu_390_p2;
wire   [7:0] tmp_56_i_i_i_fu_404_p2;
wire  signed [8:0] tmp_56_i_i_i_cast_fu_409_p1;
wire   [23:0] p_Result_s_fu_421_p3;
wire  signed [31:0] sh_assign_3_i_cast_fu_432_p1;
wire  signed [23:0] sh_assign_3_i_cast_cast_fu_435_p1;
wire   [77:0] tmp_i_i_i_fu_428_p1;
wire   [77:0] tmp_57_i_i_i_fu_438_p1;
wire   [23:0] tmp_58_i_i_i_fu_442_p2;
wire   [0:0] tmp_28_fu_454_p3;
wire   [77:0] tmp_60_i_i_i_fu_448_p2;
wire   [31:0] tmp_6_fu_462_p1;
wire   [31:0] tmp_9_fu_466_p4;
wire   [8:0] tmp_i_i_i1_i_cast1_fu_495_p1;
wire   [8:0] sh_assign_2_fu_498_p2;
wire   [7:0] tmp_56_i_i1_i_fu_512_p2;
wire  signed [8:0] tmp_56_i_i1_i_cast_fu_517_p1;
wire   [23:0] p_Result_25_fu_529_p3;
wire  signed [31:0] sh_assign_5_i_cast_fu_540_p1;
wire  signed [23:0] sh_assign_5_i_cast_cast_fu_543_p1;
wire   [77:0] tmp_i_i1_i_fu_536_p1;
wire   [77:0] tmp_57_i_i1_i_fu_546_p1;
wire   [23:0] tmp_58_i_i1_i_fu_550_p2;
wire   [0:0] tmp_32_fu_562_p3;
wire   [77:0] tmp_60_i_i1_i_fu_556_p2;
wire   [31:0] tmp_13_fu_570_p1;
wire   [31:0] tmp_14_fu_574_p4;
wire   [7:0] tmp_68_i_fu_592_p2;
wire    grp_fu_240_ce;
wire    grp_fu_244_ce;
wire    grp_fu_248_ce;
wire    grp_fu_254_ce;
wire    grp_fu_260_ce;
wire    grp_fu_264_ce;
reg    grp_fu_268_ce;
reg    ap_sig_cseq_ST_st38_fsm_37;
reg    ap_sig_bdd_718;
reg    ap_sig_cseq_ST_st39_fsm_38;
reg    ap_sig_bdd_726;
reg    ap_sig_cseq_ST_st40_fsm_39;
reg    ap_sig_bdd_734;
reg    grp_fu_271_ce;
wire    grp_fu_277_ce;
wire    grp_fu_283_ce;
reg   [71:0] ap_NS_fsm;


sinGen_CRTLS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CRTLS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CRTLS_DATA_WIDTH ))
sinGen_CRTLS_s_axi_U(
    .AWVALID( s_axi_CRTLS_AWVALID ),
    .AWREADY( s_axi_CRTLS_AWREADY ),
    .AWADDR( s_axi_CRTLS_AWADDR ),
    .WVALID( s_axi_CRTLS_WVALID ),
    .WREADY( s_axi_CRTLS_WREADY ),
    .WDATA( s_axi_CRTLS_WDATA ),
    .WSTRB( s_axi_CRTLS_WSTRB ),
    .ARVALID( s_axi_CRTLS_ARVALID ),
    .ARREADY( s_axi_CRTLS_ARREADY ),
    .ARADDR( s_axi_CRTLS_ARADDR ),
    .RVALID( s_axi_CRTLS_RVALID ),
    .RREADY( s_axi_CRTLS_RREADY ),
    .RDATA( s_axi_CRTLS_RDATA ),
    .RRESP( s_axi_CRTLS_RRESP ),
    .BVALID( s_axi_CRTLS_BVALID ),
    .BREADY( s_axi_CRTLS_BREADY ),
    .BRESP( s_axi_CRTLS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( sinGen_CRTLS_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .Fs( Fs ),
    .cycle( cycle ),
    .amp( amp ),
    .binOffset( binOffset ),
    .outIQ_address0( outIQ_address0 ),
    .outIQ_ce0( outIQ_ce0 ),
    .outIQ_we0( outIQ_we0 ),
    .outIQ_d0( outIQ_d0 )
);

sinGen_rawI #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
rawI_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( rawI_address0 ),
    .ce0( rawI_ce0 ),
    .we0( rawI_we0 ),
    .d0( rawI_d0 ),
    .q0( rawI_q0 )
);

sinGen_rawI #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
rawQ_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( rawQ_address0 ),
    .ce0( rawQ_ce0 ),
    .we0( rawQ_we0 ),
    .d0( rawQ_d0 ),
    .q0( rawQ_q0 )
);

sinGen_sinf_or_cosf grp_sinGen_sinf_or_cosf_fu_200(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_sinGen_sinf_or_cosf_fu_200_ap_start ),
    .ap_done( grp_sinGen_sinf_or_cosf_fu_200_ap_done ),
    .ap_idle( grp_sinGen_sinf_or_cosf_fu_200_ap_idle ),
    .ap_ready( grp_sinGen_sinf_or_cosf_fu_200_ap_ready ),
    .t_in( grp_sinGen_sinf_or_cosf_fu_200_t_in ),
    .do_cos( grp_sinGen_sinf_or_cosf_fu_200_do_cos ),
    .ap_return( grp_sinGen_sinf_or_cosf_fu_200_ap_return )
);

sinGen_sinf_or_cosf grp_sinGen_sinf_or_cosf_fu_215(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_sinGen_sinf_or_cosf_fu_215_ap_start ),
    .ap_done( grp_sinGen_sinf_or_cosf_fu_215_ap_done ),
    .ap_idle( grp_sinGen_sinf_or_cosf_fu_215_ap_idle ),
    .ap_ready( grp_sinGen_sinf_or_cosf_fu_215_ap_ready ),
    .t_in( grp_sinGen_sinf_or_cosf_fu_215_t_in ),
    .do_cos( grp_sinGen_sinf_or_cosf_fu_215_do_cos ),
    .ap_return( grp_sinGen_sinf_or_cosf_fu_215_ap_return )
);

sinGen_max grp_sinGen_max_fu_230(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_sinGen_max_fu_230_ap_start ),
    .ap_done( grp_sinGen_max_fu_230_ap_done ),
    .ap_idle( grp_sinGen_max_fu_230_ap_idle ),
    .ap_ready( grp_sinGen_max_fu_230_ap_ready ),
    .data_address0( grp_sinGen_max_fu_230_data_address0 ),
    .data_ce0( grp_sinGen_max_fu_230_data_ce0 ),
    .data_q0( grp_sinGen_max_fu_230_data_q0 ),
    .ap_return( grp_sinGen_max_fu_230_ap_return )
);

sinGen_max grp_sinGen_max_fu_235(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_sinGen_max_fu_235_ap_start ),
    .ap_done( grp_sinGen_max_fu_235_ap_done ),
    .ap_idle( grp_sinGen_max_fu_235_ap_idle ),
    .ap_ready( grp_sinGen_max_fu_235_ap_ready ),
    .data_address0( grp_sinGen_max_fu_235_data_address0 ),
    .data_ce0( grp_sinGen_max_fu_235_data_ce0 ),
    .data_q0( grp_sinGen_max_fu_235_data_q0 ),
    .ap_return( grp_sinGen_max_fu_235_ap_return )
);

sinGen_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fadd_32ns_32ns_32_5_full_dsp_U22(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( tmp_61_i_reg_721 ),
    .din1( tmp_i_41_reg_677 ),
    .ce( grp_fu_240_ce ),
    .dout( grp_fu_240_p2 )
);

sinGen_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fadd_32ns_32ns_32_5_full_dsp_U23(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( tmp_66_i_reg_726 ),
    .din1( tmp_i_41_reg_677 ),
    .ce( grp_fu_244_ce ),
    .dout( grp_fu_244_p2 )
);

sinGen_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fmul_32ns_32ns_32_4_max_dsp_U24(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_248_p0 ),
    .din1( grp_fu_248_p1 ),
    .ce( grp_fu_248_ce ),
    .dout( grp_fu_248_p2 )
);

sinGen_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fmul_32ns_32ns_32_4_max_dsp_U25(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_254_p0 ),
    .din1( grp_fu_254_p1 ),
    .ce( grp_fu_254_ce ),
    .dout( grp_fu_254_p2 )
);

sinGen_fdiv_32ns_32ns_32_16 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fdiv_32ns_32ns_32_16_U26(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( rawI_load_reg_701 ),
    .din1( maxI_reg_661 ),
    .ce( grp_fu_260_ce ),
    .dout( grp_fu_260_p2 )
);

sinGen_fdiv_32ns_32ns_32_16 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sinGen_fdiv_32ns_32ns_32_16_U27(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( rawQ_load_reg_706 ),
    .din1( maxQ_reg_666 ),
    .ce( grp_fu_264_ce ),
    .dout( grp_fu_264_p2 )
);

sinGen_sitofp_64ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
sinGen_sitofp_64ns_32_6_U28(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_268_p0 ),
    .ce( grp_fu_268_ce ),
    .dout( grp_fu_268_p1 )
);

sinGen_sitofp_64ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
sinGen_sitofp_64ns_32_6_U29(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_271_p0 ),
    .ce( grp_fu_271_ce ),
    .dout( grp_fu_271_p1 )
);

sinGen_fptrunc_64ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
sinGen_fptrunc_64ns_32_1_U30(
    .din0( tmp_4_reg_640 ),
    .dout( t_in_assign_fu_274_p1 )
);

sinGen_dmul_64ns_64ns_64_6_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
sinGen_dmul_64ns_64ns_64_6_max_dsp_U31(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_277_p0 ),
    .din1( grp_fu_277_p1 ),
    .ce( grp_fu_277_ce ),
    .dout( grp_fu_277_p2 )
);

sinGen_sitodp_64ns_64_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
sinGen_sitodp_64ns_64_6_U32(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_283_p0 ),
    .ce( grp_fu_283_ce ),
    .dout( grp_fu_283_p1 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_sinGen_max_fu_230_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_sinGen_max_fu_230_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
            grp_sinGen_max_fu_230_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sinGen_max_fu_230_ap_ready)) begin
            grp_sinGen_max_fu_230_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_sinGen_max_fu_235_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_sinGen_max_fu_235_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40)) begin
            grp_sinGen_max_fu_235_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sinGen_max_fu_235_ap_ready)) begin
            grp_sinGen_max_fu_235_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31)) begin
            grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sinGen_sinf_or_cosf_fu_200_ap_ready)) begin
            grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31)) begin
            grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sinGen_sinf_or_cosf_fu_215_ap_ready)) begin
            grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st72_fsm_71)) begin
        i_i_reg_188 <= i_reg_686;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41) & ~((ap_const_logic_0 == grp_sinGen_max_fu_230_ap_done) | (ap_const_logic_0 == grp_sinGen_max_fu_235_ap_done)))) begin
        i_i_reg_188 <= ap_const_lv8_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36)) begin
        idx_reg_176 <= idx_1_reg_625;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        idx_reg_176 <= ap_const_lv8_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        amp_read_reg_607 <= amp;
        binOffset_read_reg_602 <= binOffset;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42)) begin
        i_reg_686 <= i_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        idx_1_reg_625 <= idx_1_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st71_fsm_70)) begin
        isNeg_1_reg_769 <= sh_assign_2_fu_498_p2[ap_const_lv32_8];
        sh_assign_3_reg_774 <= sh_assign_3_fu_521_p3;
        tmp_29_reg_764[7 : 1] <= tmp_29_fu_484_p2[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st70_fsm_69)) begin
        isNeg_reg_753 <= sh_assign_fu_390_p2[ap_const_lv32_8];
        sh_assign_1_reg_758 <= sh_assign_1_fu_413_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st69_fsm_68)) begin
        loc_V_2_reg_737 <= loc_V_2_fu_365_p1;
        loc_V_3_reg_742 <= {{p_Val2_36_fu_369_p1[ap_const_lv32_1E : ap_const_lv32_17]}};
        loc_V_4_reg_748 <= loc_V_4_fu_383_p1;
        loc_V_reg_731 <= {{p_Val2_s_fu_351_p1[ap_const_lv32_1E : ap_const_lv32_17]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41) & ~((ap_const_logic_0 == grp_sinGen_max_fu_230_ap_done) | (ap_const_logic_0 == grp_sinGen_max_fu_235_ap_done)))) begin
        maxI_reg_661 <= grp_sinGen_max_fu_230_ap_return;
        maxQ_reg_666 <= grp_sinGen_max_fu_235_ap_return;
        tmp_i_41_reg_677 <= grp_fu_271_p1;
        tmp_i_reg_671 <= grp_fu_268_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st44_fsm_43)) begin
        rawI_load_reg_701 <= rawI_q0;
        rawQ_load_reg_706 <= rawQ_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        reg_286 <= grp_fu_283_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        reg_292 <= grp_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        t_in_assign_reg_645 <= t_in_assign_fu_274_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        tmp_4_reg_640 <= grp_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st60_fsm_59)) begin
        tmp_60_i_reg_711 <= grp_fu_260_p2;
        tmp_65_i_reg_716 <= grp_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st64_fsm_63)) begin
        tmp_61_i_reg_721 <= grp_fu_248_p2;
        tmp_66_i_reg_726 <= grp_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32) & ~((ap_const_logic_0 == grp_sinGen_sinf_or_cosf_fu_200_ap_done) | (ap_const_logic_0 == grp_sinGen_sinf_or_cosf_fu_215_ap_done)))) begin
        tmp_i_i1_reg_656 <= grp_sinGen_sinf_or_cosf_fu_215_ap_return;
        tmp_i_i_reg_651 <= grp_sinGen_sinf_or_cosf_fu_200_ap_return;
    end
end

always @ (ap_sig_cseq_ST_st43_fsm_42 or exitcond_i_fu_333_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42) & ~(ap_const_lv1_0 == exitcond_i_fu_333_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st43_fsm_42 or exitcond_i_fu_333_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42) & ~(ap_const_lv1_0 == exitcond_i_fu_333_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_167) begin
    if (ap_sig_bdd_167) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_555) begin
    if (ap_sig_bdd_555) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_174) begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_193) begin
    if (ap_sig_bdd_193) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_90) begin
    if (ap_sig_bdd_90) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_157) begin
    if (ap_sig_bdd_157) begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_562) begin
    if (ap_sig_bdd_562) begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_212) begin
    if (ap_sig_bdd_212) begin
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_221) begin
    if (ap_sig_bdd_221) begin
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_422) begin
    if (ap_sig_bdd_422) begin
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_230) begin
    if (ap_sig_bdd_230) begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_514) begin
    if (ap_sig_bdd_514) begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_404) begin
    if (ap_sig_bdd_404) begin
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_718) begin
    if (ap_sig_bdd_718) begin
        ap_sig_cseq_ST_st38_fsm_37 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st38_fsm_37 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_726) begin
    if (ap_sig_bdd_726) begin
        ap_sig_cseq_ST_st39_fsm_38 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st39_fsm_38 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_734) begin
    if (ap_sig_bdd_734) begin
        ap_sig_cseq_ST_st40_fsm_39 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st40_fsm_39 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_477) begin
    if (ap_sig_bdd_477) begin
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_248) begin
    if (ap_sig_bdd_248) begin
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_270) begin
    if (ap_sig_bdd_270) begin
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_286) begin
    if (ap_sig_bdd_286) begin
        ap_sig_cseq_ST_st44_fsm_43 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st44_fsm_43 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_297) begin
    if (ap_sig_bdd_297) begin
        ap_sig_cseq_ST_st60_fsm_59 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st60_fsm_59 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_521) begin
    if (ap_sig_bdd_521) begin
        ap_sig_cseq_ST_st61_fsm_60 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st61_fsm_60 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_308) begin
    if (ap_sig_bdd_308) begin
        ap_sig_cseq_ST_st64_fsm_63 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st64_fsm_63 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_319) begin
    if (ap_sig_bdd_319) begin
        ap_sig_cseq_ST_st69_fsm_68 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st69_fsm_68 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_150) begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_334) begin
    if (ap_sig_bdd_334) begin
        ap_sig_cseq_ST_st70_fsm_69 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st70_fsm_69 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_345) begin
    if (ap_sig_bdd_345) begin
        ap_sig_cseq_ST_st71_fsm_70 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st71_fsm_70 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_413) begin
    if (ap_sig_bdd_413) begin
        ap_sig_cseq_ST_st72_fsm_71 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st72_fsm_71 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_548) begin
    if (ap_sig_bdd_548) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (tmp_i_i_reg_651 or tmp_60_i_reg_711 or ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st61_fsm_60) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st61_fsm_60)) begin
        grp_fu_248_p0 = tmp_60_i_reg_711;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_fu_248_p0 = tmp_i_i_reg_651;
    end else begin
        grp_fu_248_p0 = 'bx;
    end
end

always @ (tmp_i_reg_671 or ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st61_fsm_60) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st61_fsm_60)) begin
        grp_fu_248_p1 = tmp_i_reg_671;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_fu_248_p1 = ap_const_lv32_40800000;
    end else begin
        grp_fu_248_p1 = 'bx;
    end
end

always @ (tmp_i_i1_reg_656 or tmp_65_i_reg_716 or ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st61_fsm_60) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st61_fsm_60)) begin
        grp_fu_254_p0 = tmp_65_i_reg_716;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_fu_254_p0 = tmp_i_i1_reg_656;
    end else begin
        grp_fu_254_p0 = 'bx;
    end
end

always @ (tmp_i_reg_671 or ap_sig_cseq_ST_st34_fsm_33 or ap_sig_cseq_ST_st61_fsm_60) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st61_fsm_60)) begin
        grp_fu_254_p1 = tmp_i_reg_671;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_fu_254_p1 = ap_const_lv32_40800000;
    end else begin
        grp_fu_254_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st19_fsm_18 or ap_sig_cseq_ST_st42_fsm_41 or grp_sinGen_max_fu_230_ap_done or grp_sinGen_max_fu_235_ap_done or ap_sig_cseq_ST_st41_fsm_40 or ap_sig_cseq_ST_st38_fsm_37 or ap_sig_cseq_ST_st39_fsm_38 or ap_sig_cseq_ST_st40_fsm_39) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) | ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41) & ~((ap_const_logic_0 == grp_sinGen_max_fu_230_ap_done) | (ap_const_logic_0 == grp_sinGen_max_fu_235_ap_done))) | (ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40) | (ap_const_logic_1 == ap_sig_cseq_ST_st38_fsm_37) | (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_38) | (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_39))) begin
        grp_fu_268_ce = ap_const_logic_1;
    end else begin
        grp_fu_268_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st19_fsm_18 or ap_sig_cseq_ST_st42_fsm_41 or grp_sinGen_max_fu_230_ap_done or grp_sinGen_max_fu_235_ap_done or ap_sig_cseq_ST_st41_fsm_40 or ap_sig_cseq_ST_st38_fsm_37 or ap_sig_cseq_ST_st39_fsm_38 or ap_sig_cseq_ST_st40_fsm_39) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) | ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41) & ~((ap_const_logic_0 == grp_sinGen_max_fu_230_ap_done) | (ap_const_logic_0 == grp_sinGen_max_fu_235_ap_done))) | (ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_40) | (ap_const_logic_1 == ap_sig_cseq_ST_st38_fsm_37) | (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_38) | (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_39))) begin
        grp_fu_271_ce = ap_const_logic_1;
    end else begin
        grp_fu_271_ce = ap_const_logic_0;
    end
end

always @ (reg_286 or reg_292 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st25_fsm_24) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24))) begin
        grp_fu_277_p0 = reg_292;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_fu_277_p0 = reg_286;
    end else begin
        grp_fu_277_p0 = 'bx;
    end
end

always @ (reg_286 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st25_fsm_24) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24)) begin
        grp_fu_277_p1 = reg_286;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_277_p1 = ap_const_lv64_3F80000000000000;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_fu_277_p1 = ap_const_lv64_40091EB851EB851F;
    end else begin
        grp_fu_277_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or cycle5_fu_297_p1 or idx_cast4_fu_302_p1 or ap_sig_cseq_ST_st19_fsm_18) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        grp_fu_283_p0 = idx_cast4_fu_302_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        grp_fu_283_p0 = cycle5_fu_297_p1;
    end else begin
        grp_fu_283_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st71_fsm_70 or ap_sig_cseq_ST_st72_fsm_71 or tmp_64_i_fu_490_p1 or tmp_69_i_fu_597_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st72_fsm_71)) begin
        outIQ_address0 = tmp_69_i_fu_597_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st71_fsm_70)) begin
        outIQ_address0 = tmp_64_i_fu_490_p1;
    end else begin
        outIQ_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st71_fsm_70 or ap_sig_cseq_ST_st72_fsm_71) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st71_fsm_70) | (ap_const_logic_1 == ap_sig_cseq_ST_st72_fsm_71))) begin
        outIQ_ce0 = ap_const_logic_1;
    end else begin
        outIQ_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st71_fsm_70 or ap_sig_cseq_ST_st72_fsm_71 or result_V_fu_476_p3 or result_V_1_fu_584_p3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st72_fsm_71)) begin
        outIQ_d0 = result_V_1_fu_584_p3;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st71_fsm_70)) begin
        outIQ_d0 = result_V_fu_476_p3;
    end else begin
        outIQ_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st71_fsm_70 or ap_sig_cseq_ST_st72_fsm_71) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st71_fsm_70) | (ap_const_logic_1 == ap_sig_cseq_ST_st72_fsm_71))) begin
        outIQ_we0 = ap_const_logic_1;
    end else begin
        outIQ_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st42_fsm_41 or ap_sig_cseq_ST_st43_fsm_42 or grp_sinGen_max_fu_230_data_address0 or ap_sig_cseq_ST_st37_fsm_36 or tmp_8_fu_327_p1 or tmp_59_i_fu_345_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36)) begin
        rawI_address0 = tmp_8_fu_327_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42)) begin
        rawI_address0 = tmp_59_i_fu_345_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41)) begin
        rawI_address0 = grp_sinGen_max_fu_230_data_address0;
    end else begin
        rawI_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st42_fsm_41 or ap_sig_cseq_ST_st43_fsm_42 or grp_sinGen_max_fu_230_data_ce0 or ap_sig_cseq_ST_st37_fsm_36) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42) | (ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36))) begin
        rawI_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41)) begin
        rawI_ce0 = grp_sinGen_max_fu_230_data_ce0;
    end else begin
        rawI_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st37_fsm_36) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36)) begin
        rawI_we0 = ap_const_logic_1;
    end else begin
        rawI_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st42_fsm_41 or ap_sig_cseq_ST_st43_fsm_42 or grp_sinGen_max_fu_235_data_address0 or ap_sig_cseq_ST_st37_fsm_36 or tmp_8_fu_327_p1 or tmp_59_i_fu_345_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36)) begin
        rawQ_address0 = tmp_8_fu_327_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42)) begin
        rawQ_address0 = tmp_59_i_fu_345_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41)) begin
        rawQ_address0 = grp_sinGen_max_fu_235_data_address0;
    end else begin
        rawQ_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st42_fsm_41 or ap_sig_cseq_ST_st43_fsm_42 or grp_sinGen_max_fu_235_data_ce0 or ap_sig_cseq_ST_st37_fsm_36) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42) | (ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36))) begin
        rawQ_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_41)) begin
        rawQ_ce0 = grp_sinGen_max_fu_235_data_ce0;
    end else begin
        rawQ_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st37_fsm_36) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st37_fsm_36)) begin
        rawQ_we0 = ap_const_logic_1;
    end else begin
        rawQ_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond_fu_307_p2 or grp_sinGen_sinf_or_cosf_fu_200_ap_done or grp_sinGen_sinf_or_cosf_fu_215_ap_done or grp_sinGen_max_fu_230_ap_done or grp_sinGen_max_fu_235_ap_done or exitcond_i_fu_333_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : 
        begin
            if (~(exitcond_fu_307_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st38_fsm_37;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st20_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st21_fsm_20;
        end
        ap_ST_st21_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st22_fsm_21;
        end
        ap_ST_st22_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st23_fsm_22;
        end
        ap_ST_st23_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st25_fsm_24;
        end
        ap_ST_st25_fsm_24 : 
        begin
            ap_NS_fsm = ap_ST_st26_fsm_25;
        end
        ap_ST_st26_fsm_25 : 
        begin
            ap_NS_fsm = ap_ST_st27_fsm_26;
        end
        ap_ST_st27_fsm_26 : 
        begin
            ap_NS_fsm = ap_ST_st28_fsm_27;
        end
        ap_ST_st28_fsm_27 : 
        begin
            ap_NS_fsm = ap_ST_st29_fsm_28;
        end
        ap_ST_st29_fsm_28 : 
        begin
            ap_NS_fsm = ap_ST_st30_fsm_29;
        end
        ap_ST_st30_fsm_29 : 
        begin
            ap_NS_fsm = ap_ST_st31_fsm_30;
        end
        ap_ST_st31_fsm_30 : 
        begin
            ap_NS_fsm = ap_ST_st32_fsm_31;
        end
        ap_ST_st32_fsm_31 : 
        begin
            ap_NS_fsm = ap_ST_st33_fsm_32;
        end
        ap_ST_st33_fsm_32 : 
        begin
            if (~((ap_const_logic_0 == grp_sinGen_sinf_or_cosf_fu_200_ap_done) | (ap_const_logic_0 == grp_sinGen_sinf_or_cosf_fu_215_ap_done))) begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end else begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end
        end
        ap_ST_st34_fsm_33 : 
        begin
            ap_NS_fsm = ap_ST_st35_fsm_34;
        end
        ap_ST_st35_fsm_34 : 
        begin
            ap_NS_fsm = ap_ST_st36_fsm_35;
        end
        ap_ST_st36_fsm_35 : 
        begin
            ap_NS_fsm = ap_ST_st37_fsm_36;
        end
        ap_ST_st37_fsm_36 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st38_fsm_37 : 
        begin
            ap_NS_fsm = ap_ST_st39_fsm_38;
        end
        ap_ST_st39_fsm_38 : 
        begin
            ap_NS_fsm = ap_ST_st40_fsm_39;
        end
        ap_ST_st40_fsm_39 : 
        begin
            ap_NS_fsm = ap_ST_st41_fsm_40;
        end
        ap_ST_st41_fsm_40 : 
        begin
            ap_NS_fsm = ap_ST_st42_fsm_41;
        end
        ap_ST_st42_fsm_41 : 
        begin
            if (~((ap_const_logic_0 == grp_sinGen_max_fu_230_ap_done) | (ap_const_logic_0 == grp_sinGen_max_fu_235_ap_done))) begin
                ap_NS_fsm = ap_ST_st43_fsm_42;
            end else begin
                ap_NS_fsm = ap_ST_st42_fsm_41;
            end
        end
        ap_ST_st43_fsm_42 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_i_fu_333_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st44_fsm_43;
            end
        end
        ap_ST_st44_fsm_43 : 
        begin
            ap_NS_fsm = ap_ST_st45_fsm_44;
        end
        ap_ST_st45_fsm_44 : 
        begin
            ap_NS_fsm = ap_ST_st46_fsm_45;
        end
        ap_ST_st46_fsm_45 : 
        begin
            ap_NS_fsm = ap_ST_st47_fsm_46;
        end
        ap_ST_st47_fsm_46 : 
        begin
            ap_NS_fsm = ap_ST_st48_fsm_47;
        end
        ap_ST_st48_fsm_47 : 
        begin
            ap_NS_fsm = ap_ST_st49_fsm_48;
        end
        ap_ST_st49_fsm_48 : 
        begin
            ap_NS_fsm = ap_ST_st50_fsm_49;
        end
        ap_ST_st50_fsm_49 : 
        begin
            ap_NS_fsm = ap_ST_st51_fsm_50;
        end
        ap_ST_st51_fsm_50 : 
        begin
            ap_NS_fsm = ap_ST_st52_fsm_51;
        end
        ap_ST_st52_fsm_51 : 
        begin
            ap_NS_fsm = ap_ST_st53_fsm_52;
        end
        ap_ST_st53_fsm_52 : 
        begin
            ap_NS_fsm = ap_ST_st54_fsm_53;
        end
        ap_ST_st54_fsm_53 : 
        begin
            ap_NS_fsm = ap_ST_st55_fsm_54;
        end
        ap_ST_st55_fsm_54 : 
        begin
            ap_NS_fsm = ap_ST_st56_fsm_55;
        end
        ap_ST_st56_fsm_55 : 
        begin
            ap_NS_fsm = ap_ST_st57_fsm_56;
        end
        ap_ST_st57_fsm_56 : 
        begin
            ap_NS_fsm = ap_ST_st58_fsm_57;
        end
        ap_ST_st58_fsm_57 : 
        begin
            ap_NS_fsm = ap_ST_st59_fsm_58;
        end
        ap_ST_st59_fsm_58 : 
        begin
            ap_NS_fsm = ap_ST_st60_fsm_59;
        end
        ap_ST_st60_fsm_59 : 
        begin
            ap_NS_fsm = ap_ST_st61_fsm_60;
        end
        ap_ST_st61_fsm_60 : 
        begin
            ap_NS_fsm = ap_ST_st62_fsm_61;
        end
        ap_ST_st62_fsm_61 : 
        begin
            ap_NS_fsm = ap_ST_st63_fsm_62;
        end
        ap_ST_st63_fsm_62 : 
        begin
            ap_NS_fsm = ap_ST_st64_fsm_63;
        end
        ap_ST_st64_fsm_63 : 
        begin
            ap_NS_fsm = ap_ST_st65_fsm_64;
        end
        ap_ST_st65_fsm_64 : 
        begin
            ap_NS_fsm = ap_ST_st66_fsm_65;
        end
        ap_ST_st66_fsm_65 : 
        begin
            ap_NS_fsm = ap_ST_st67_fsm_66;
        end
        ap_ST_st67_fsm_66 : 
        begin
            ap_NS_fsm = ap_ST_st68_fsm_67;
        end
        ap_ST_st68_fsm_67 : 
        begin
            ap_NS_fsm = ap_ST_st69_fsm_68;
        end
        ap_ST_st69_fsm_68 : 
        begin
            ap_NS_fsm = ap_ST_st70_fsm_69;
        end
        ap_ST_st70_fsm_69 : 
        begin
            ap_NS_fsm = ap_ST_st71_fsm_70;
        end
        ap_ST_st71_fsm_70 : 
        begin
            ap_NS_fsm = ap_ST_st72_fsm_71;
        end
        ap_ST_st72_fsm_71 : 
        begin
            ap_NS_fsm = ap_ST_st43_fsm_42;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_157 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_167 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_193 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_212 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_221 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_230 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_20]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_248 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_29]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_270 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_286 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_297 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_308 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_319 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_44]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_334 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_45]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_345 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_46]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_404 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_24]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_413 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_47]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_422 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_477 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_28]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_514 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_21]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_521 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_548 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_555 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_562 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_18]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_718 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_25]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_726 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_26]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_734 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_27]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_90 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

assign cycle5_fu_297_p1 = cycle;

assign exitcond_fu_307_p2 = (idx_reg_176 == ap_const_lv8_80? 1'b1: 1'b0);

assign exitcond_i_fu_333_p2 = (i_i_reg_188 == ap_const_lv8_80? 1'b1: 1'b0);

assign grp_fu_240_ce = ap_const_logic_1;

assign grp_fu_244_ce = ap_const_logic_1;

assign grp_fu_248_ce = ap_const_logic_1;

assign grp_fu_254_ce = ap_const_logic_1;

assign grp_fu_260_ce = ap_const_logic_1;

assign grp_fu_264_ce = ap_const_logic_1;

assign grp_fu_268_p0 = amp_read_reg_607;

assign grp_fu_271_p0 = binOffset_read_reg_602;

assign grp_fu_277_ce = ap_const_logic_1;

assign grp_fu_283_ce = ap_const_logic_1;

assign grp_sinGen_max_fu_230_ap_start = grp_sinGen_max_fu_230_ap_start_ap_start_reg;

assign grp_sinGen_max_fu_230_data_q0 = rawI_q0;

assign grp_sinGen_max_fu_235_ap_start = grp_sinGen_max_fu_235_ap_start_ap_start_reg;

assign grp_sinGen_max_fu_235_data_q0 = rawQ_q0;

assign grp_sinGen_sinf_or_cosf_fu_200_ap_start = grp_sinGen_sinf_or_cosf_fu_200_ap_start_ap_start_reg;

assign grp_sinGen_sinf_or_cosf_fu_200_do_cos = ap_const_lv1_0;

assign grp_sinGen_sinf_or_cosf_fu_200_t_in = t_in_assign_reg_645;

assign grp_sinGen_sinf_or_cosf_fu_215_ap_start = grp_sinGen_sinf_or_cosf_fu_215_ap_start_ap_start_reg;

assign grp_sinGen_sinf_or_cosf_fu_215_do_cos = ap_const_lv1_1;

assign grp_sinGen_sinf_or_cosf_fu_215_t_in = t_in_assign_reg_645;

assign i_fu_339_p2 = (i_i_reg_188 + ap_const_lv8_1);

assign idx_1_fu_313_p2 = (idx_reg_176 + ap_const_lv8_1);

assign idx_cast4_fu_302_p1 = idx_reg_176;

assign isNeg_1_fu_504_p3 = sh_assign_2_fu_498_p2[ap_const_lv32_8];

assign isNeg_fu_396_p3 = sh_assign_fu_390_p2[ap_const_lv32_8];

assign loc_V_2_fu_365_p1 = p_Val2_s_fu_351_p1[22:0];

assign loc_V_4_fu_383_p1 = p_Val2_36_fu_369_p1[22:0];

assign p_Result_25_fu_529_p3 = {{ap_const_lv1_1}, {loc_V_4_reg_748}};

assign p_Result_s_fu_421_p3 = {{ap_const_lv1_1}, {loc_V_2_reg_737}};

assign p_Val2_36_fu_369_p1 = grp_fu_244_p2;

assign p_Val2_s_fu_351_p1 = grp_fu_240_p2;

assign rawI_d0 = grp_fu_248_p2;

assign rawQ_d0 = grp_fu_254_p2;

assign result_V_1_fu_584_p3 = ((isNeg_1_reg_769[0:0] === 1'b1) ? tmp_13_fu_570_p1 : tmp_14_fu_574_p4);

assign result_V_fu_476_p3 = ((isNeg_reg_753[0:0] === 1'b1) ? tmp_6_fu_462_p1 : tmp_9_fu_466_p4);

assign sh_assign_1_fu_413_p3 = ((isNeg_fu_396_p3[0:0] === 1'b1) ? tmp_56_i_i_i_cast_fu_409_p1 : sh_assign_fu_390_p2);

assign sh_assign_2_fu_498_p2 = ($signed(ap_const_lv9_181) + $signed(tmp_i_i_i1_i_cast1_fu_495_p1));

assign sh_assign_3_fu_521_p3 = ((isNeg_1_fu_504_p3[0:0] === 1'b1) ? tmp_56_i_i1_i_cast_fu_517_p1 : sh_assign_2_fu_498_p2);

assign sh_assign_3_i_cast_cast_fu_435_p1 = $signed(sh_assign_1_reg_758);

assign sh_assign_3_i_cast_fu_432_p1 = $signed(sh_assign_1_reg_758);

assign sh_assign_5_i_cast_cast_fu_543_p1 = $signed(sh_assign_3_reg_774);

assign sh_assign_5_i_cast_fu_540_p1 = $signed(sh_assign_3_reg_774);

assign sh_assign_fu_390_p2 = ($signed(ap_const_lv9_181) + $signed(tmp_i_i_i_i_cast2_fu_387_p1));

assign sinGen_CRTLS_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign tmp_13_fu_570_p1 = tmp_32_fu_562_p3;

assign tmp_14_fu_574_p4 = {{tmp_60_i_i1_i_fu_556_p2[ap_const_lv32_36 : ap_const_lv32_17]}};

assign tmp_28_fu_454_p3 = tmp_58_i_i_i_fu_442_p2[ap_const_lv32_17];

assign tmp_29_fu_484_p2 = i_i_reg_188 << ap_const_lv8_1;

assign tmp_32_fu_562_p3 = tmp_58_i_i1_i_fu_550_p2[ap_const_lv32_17];

assign tmp_56_i_i1_i_cast_fu_517_p1 = $signed(tmp_56_i_i1_i_fu_512_p2);

assign tmp_56_i_i1_i_fu_512_p2 = (ap_const_lv8_7F - loc_V_3_reg_742);

assign tmp_56_i_i_i_cast_fu_409_p1 = $signed(tmp_56_i_i_i_fu_404_p2);

assign tmp_56_i_i_i_fu_404_p2 = (ap_const_lv8_7F - loc_V_reg_731);

assign tmp_57_i_i1_i_fu_546_p1 = $unsigned(sh_assign_5_i_cast_fu_540_p1);

assign tmp_57_i_i_i_fu_438_p1 = $unsigned(sh_assign_3_i_cast_fu_432_p1);

assign tmp_58_i_i1_i_fu_550_p2 = p_Result_25_fu_529_p3 >> sh_assign_5_i_cast_cast_fu_543_p1;

assign tmp_58_i_i_i_fu_442_p2 = p_Result_s_fu_421_p3 >> sh_assign_3_i_cast_cast_fu_435_p1;

assign tmp_59_i_fu_345_p1 = i_i_reg_188;

assign tmp_60_i_i1_i_fu_556_p2 = tmp_i_i1_i_fu_536_p1 << tmp_57_i_i1_i_fu_546_p1;

assign tmp_60_i_i_i_fu_448_p2 = tmp_i_i_i_fu_428_p1 << tmp_57_i_i_i_fu_438_p1;

assign tmp_64_i_fu_490_p1 = tmp_29_fu_484_p2;

assign tmp_68_i_fu_592_p2 = (tmp_29_reg_764 | ap_const_lv8_1);

assign tmp_69_i_fu_597_p1 = tmp_68_i_fu_592_p2;

assign tmp_6_fu_462_p1 = tmp_28_fu_454_p3;

assign tmp_8_fu_327_p1 = idx_reg_176;

assign tmp_9_fu_466_p4 = {{tmp_60_i_i_i_fu_448_p2[ap_const_lv32_36 : ap_const_lv32_17]}};

assign tmp_i_i1_i_fu_536_p1 = p_Result_25_fu_529_p3;

assign tmp_i_i_i1_i_cast1_fu_495_p1 = loc_V_3_reg_742;

assign tmp_i_i_i_fu_428_p1 = p_Result_s_fu_421_p3;

assign tmp_i_i_i_i_cast2_fu_387_p1 = loc_V_reg_731;
always @ (posedge ap_clk) begin
    tmp_29_reg_764[0] <= 1'b0;
end



endmodule //sinGen

