webtalk_init -webtalk_dir E:\\ZedBoard_Projects\\FmComms_Lan\\fmcomms1_zed.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 13 18:01:50 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pmaamhqu0lk9k61qk9ddkbum7m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1534143643405" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1534143643405"
webtalk_add_data -client sdk -key uid -value "1534143705461" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4.2" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1534143705461"
webtalk_add_data -client sdk -key uid -value "1534143720559" -context "sdk\\\\bsp/1534143720559"
webtalk_add_data -client sdk -key hwid -value "1534143705461" -context "sdk\\\\bsp/1534143720559"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1534143720559"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1534143720559"
webtalk_add_data -client sdk -key uid -value "1534143722943" -context "sdk\\\\application/1534143722943"
webtalk_add_data -client sdk -key hwid -value "1534143705461" -context "sdk\\\\application/1534143722943"
webtalk_add_data -client sdk -key bspid -value "1534143720559" -context "sdk\\\\application/1534143722943"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1534143722943"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1534143722943"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1534143722943"
webtalk_transmit -clientid 2778764180 -regid "" -xml E:\\ZedBoard_Projects\\FmComms_Lan\\fmcomms1_zed.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\ZedBoard_Projects\\FmComms_Lan\\fmcomms1_zed.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\ZedBoard_Projects\\FmComms_Lan\\fmcomms1_zed.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
