set_property SRC_FILE_INFO {cfile:E:/ZedBoard_Projects/SIN_BRAM/zed/system_constr.xdc rfile:../../../system_constr.xdc id:1 order:EARLY} [current_design]
set_property SRC_FILE_INFO {cfile:C:/cygwin64/home/Dr-Abbasfar/adi/hdl/projects/common/zed/zed_system_constr.xdc rfile:C:/cygwin64/home/Dr-Abbasfar/adi/hdl/projects/common/zed/zed_system_constr.xdc id:2 order:EARLY} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc id:3 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_ps7/inst} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc id:4 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_audio_clkgen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_refclk_clkgen_0/system_refclk_clkgen_0.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_refclk_clkgen_0/system_refclk_clkgen_0.xdc id:5 order:EARLY scoped_inst:i_system_wrapper/system_i/refclk_clkgen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_i2s_adi_0/axi_i2s_adi_constr.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_i2s_adi_0/axi_i2s_adi_constr.xdc id:6 order:LATE scoped_inst:i_system_wrapper/system_i/axi_i2s_adi} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_ad9122_dma_0/system_axi_ad9122_dma_0_constr.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_ad9122_dma_0/system_axi_ad9122_dma_0_constr.xdc id:7 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9122_dma} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_ad9643_dma_0/system_axi_ad9643_dma_0_constr.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_axi_ad9643_dma_0/system_axi_ad9643_dma_0_constr.xdc id:8 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9643_dma} [current_design]
set_property SRC_FILE_INFO {cfile:e:/ZedBoard_Projects/SIN_BRAM/zed/fmcomms1_zed.srcs/sources_1/bd/system/ip/system_util_ad9643_adc_fifo_0/util_wfifo_constr.xdc rfile:../../../fmcomms1_zed.srcs/sources_1/bd/system/ip/system_util_ad9643_adc_fifo_0/util_wfifo_constr.xdc id:9 order:LATE scoped_inst:i_system_wrapper/system_i/util_ad9643_adc_fifo} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports ref_clk_out_p]       ; ## FMC1_LPC_LA17_CC_P
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports ref_clk_out_n]       ; ## FMC1_LPC_LA17_CC_N
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L18   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports dac_clk_in_p]        ; ## FMC1_LPC_CLK0_M2C_P
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports dac_clk_in_n]        ; ## FMC1_LPC_CLK0_M2C_N
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E19   IOSTANDARD LVDS_25} [get_ports dac_clk_out_p]                      ; ## FMC1_LPC_LA21_P
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E20   IOSTANDARD LVDS_25} [get_ports dac_clk_out_n]                      ; ## FMC1_LPC_LA21_N
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N17   IOSTANDARD LVDS_25} [get_ports dac_frame_out_p]                    ; ## FMC1_LPC_LA11_P
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N18   IOSTANDARD LVDS_25} [get_ports dac_frame_out_n]                    ; ## FMC1_LPC_LA11_N
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A21   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[0]]                  ; ## FMC1_LPC_LA32_P
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A22   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[0]]                  ; ## FMC1_LPC_LA32_N
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B21   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[1]]                  ; ## FMC1_LPC_LA33_P
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B22   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[1]]                  ; ## FMC1_LPC_LA33_N
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C15   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[2]]                  ; ## FMC1_LPC_LA30_P
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B15   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[2]]                  ; ## FMC1_LPC_LA30_N
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A16   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[3]]                  ; ## FMC1_LPC_LA28_P
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A17   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[3]]                  ; ## FMC1_LPC_LA28_N
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B16   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[4]]                  ; ## FMC1_LPC_LA31_P
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN B17   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[4]]                  ; ## FMC1_LPC_LA31_N
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C17   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[5]]                  ; ## FMC1_LPC_LA29_P
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C18   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[5]]                  ; ## FMC1_LPC_LA29_N
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A18   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[6]]                  ; ## FMC1_LPC_LA24_P
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A19   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[6]]                  ; ## FMC1_LPC_LA24_N
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D22   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[7]]                  ; ## FMC1_LPC_LA25_P
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C22   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[7]]                  ; ## FMC1_LPC_LA25_N
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G19   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[8]]                  ; ## FMC1_LPC_LA22_P
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN F19   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[8]]                  ; ## FMC1_LPC_LA22_N
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E21   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[9]]                  ; ## FMC1_LPC_LA27_P
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D21   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[9]]                  ; ## FMC1_LPC_LA27_N
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN F18   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[10]]                 ; ## FMC1_LPC_LA26_P
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E18   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[10]]                 ; ## FMC1_LPC_LA26_N
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E15   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[11]]                 ; ## FMC1_LPC_LA23_P
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D15   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[11]]                 ; ## FMC1_LPC_LA23_N
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G15   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[12]]                 ; ## FMC1_LPC_LA19_P
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G16   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[12]]                 ; ## FMC1_LPC_LA19_N
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G20   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[13]]                 ; ## FMC1_LPC_LA20_P
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G21   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[13]]                 ; ## FMC1_LPC_LA20_N
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J16   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[14]]                 ; ## FMC1_LPC_LA15_P
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J17   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[14]]                 ; ## FMC1_LPC_LA15_N
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J20   IOSTANDARD LVDS_25} [get_ports dac_data_out_p[15]]                 ; ## FMC1_LPC_LA16_P
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K21   IOSTANDARD LVDS_25} [get_ports dac_data_out_n[15]]                 ; ## FMC1_LPC_LA16_N
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D18   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_clk_in_p]        ; ## FMC1_LPC_CLK1_M2C_P
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_clk_in_n]        ; ## FMC1_LPC_CLK1_M2C_N
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_or_in_p]         ; ## FMC1_LPC_LA00_CC_P
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_or_in_n]         ; ## FMC1_LPC_LA00_CC_N
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[0]]    ; ## FMC1_LPC_LA18_CC_P
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[0]]    ; ## FMC1_LPC_LA18_CC_N
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[1]]    ; ## FMC1_LPC_LA14_P
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[1]]    ; ## FMC1_LPC_LA14_N
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L17   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[2]]    ; ## FMC1_LPC_LA13_P
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M17   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[2]]    ; ## FMC1_LPC_LA13_N
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N22   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[3]]    ; ## FMC1_LPC_LA03_P
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P22   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[3]]    ; ## FMC1_LPC_LA03_N
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J18   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[4]]    ; ## FMC1_LPC_LA05_P
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K18   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[4]]    ; ## FMC1_LPC_LA05_N
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[5]]    ; ## FMC1_LPC_LA10_P
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[5]]    ; ## FMC1_LPC_LA10_N
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[6]]    ; ## FMC1_LPC_LA12_P
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P21   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[6]]    ; ## FMC1_LPC_LA12_N
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T16   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[7]]    ; ## FMC1_LPC_LA07_P
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T17   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[7]]    ; ## FMC1_LPC_LA07_N
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P17   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[8]]    ; ## FMC1_LPC_LA02_P
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P18   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[8]]    ; ## FMC1_LPC_LA02_N
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M21   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[9]]    ; ## FMC1_LPC_LA04_P
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M22   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[9]]    ; ## FMC1_LPC_LA04_N
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[10]]   ; ## FMC1_LPC_LA09_P
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R21   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[10]]   ; ## FMC1_LPC_LA09_N
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J21   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[11]]   ; ## FMC1_LPC_LA08_P
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J22   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[11]]   ; ## FMC1_LPC_LA08_N
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L21   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[12]]   ; ## FMC1_LPC_LA06_P
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L22   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[12]]   ; ## FMC1_LPC_LA06_N
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N19   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_p[13]]   ; ## FMC1_LPC_LA01_CC_P
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N20   IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports adc_data_in_n[13]]   ; ## FMC1_LPC_LA01_CC_N
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W18   IOSTANDARD LVCMOS33}           [get_ports hdmi_out_clk]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W17   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_vsync]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V17   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_hsync]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U16   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data_e]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y13   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[0]]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA13  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[1]]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA14  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[2]]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y14   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[3]]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB15  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[4]]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB16  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[5]]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA16  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[6]]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB17  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[7]]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA17  IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[8]]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y15   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[9]]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W13   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[10]]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W15   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[11]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V15   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[12]]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U17   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[13]]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V14   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[14]]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V13   IOSTANDARD LVCMOS33  IOB TRUE} [get_ports hdmi_data[15]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U15   IOSTANDARD LVCMOS33} [get_ports spdif]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB2   IOSTANDARD LVCMOS33} [get_ports i2s_mclk]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA6   IOSTANDARD LVCMOS33} [get_ports i2s_bclk]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y6    IOSTANDARD LVCMOS33} [get_ports i2s_lrclk]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y8    IOSTANDARD LVCMOS33} [get_ports i2s_sdata_out]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA7   IOSTANDARD LVCMOS33} [get_ports i2s_sdata_in]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R7    IOSTANDARD LVCMOS33} [get_ports iic_scl]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U7    IOSTANDARD LVCMOS33} [get_ports iic_sda]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA18  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_mux_scl[1]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y16   IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_mux_sda[1]]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB4   IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_mux_scl[0]]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB5   IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_mux_sda[0]]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L16   IOSTANDARD LVCMOS25} [get_ports otg_vbusoc]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P16   IOSTANDARD LVCMOS25} [get_ports gpio_bd[0]]       ; ## BTNC
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R16   IOSTANDARD LVCMOS25} [get_ports gpio_bd[1]]       ; ## BTND
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[2]]       ; ## BTNL
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R18   IOSTANDARD LVCMOS25} [get_ports gpio_bd[3]]       ; ## BTNR
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T18   IOSTANDARD LVCMOS25} [get_ports gpio_bd[4]]       ; ## BTNU
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U10   IOSTANDARD LVCMOS33} [get_ports gpio_bd[5]]       ; ## OLED-DC
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U9    IOSTANDARD LVCMOS33} [get_ports gpio_bd[6]]       ; ## OLED-RES
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB12  IOSTANDARD LVCMOS33} [get_ports gpio_bd[7]]       ; ## OLED-SCLK
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA12  IOSTANDARD LVCMOS33} [get_ports gpio_bd[8]]       ; ## OLED-SDIN
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U11   IOSTANDARD LVCMOS33} [get_ports gpio_bd[9]]       ; ## OLED-VBAT
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U12   IOSTANDARD LVCMOS33} [get_ports gpio_bd[10]]      ; ## OLED-VDD
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F22   IOSTANDARD LVCMOS25} [get_ports gpio_bd[11]]      ; ## SW0
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G22   IOSTANDARD LVCMOS25} [get_ports gpio_bd[12]]      ; ## SW1
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H22   IOSTANDARD LVCMOS25} [get_ports gpio_bd[13]]      ; ## SW2
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  F21   IOSTANDARD LVCMOS25} [get_ports gpio_bd[14]]      ; ## SW3
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H19   IOSTANDARD LVCMOS25} [get_ports gpio_bd[15]]      ; ## SW4
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H18   IOSTANDARD LVCMOS25} [get_ports gpio_bd[16]]      ; ## SW5
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H17   IOSTANDARD LVCMOS25} [get_ports gpio_bd[17]]      ; ## SW6
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  M15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[18]]      ; ## SW7
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T22   IOSTANDARD LVCMOS33} [get_ports gpio_bd[19]]      ; ## LD0
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T21   IOSTANDARD LVCMOS33} [get_ports gpio_bd[20]]      ; ## LD1
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U22   IOSTANDARD LVCMOS33} [get_ports gpio_bd[21]]      ; ## LD2
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U21   IOSTANDARD LVCMOS33} [get_ports gpio_bd[22]]      ; ## LD3
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V22   IOSTANDARD LVCMOS33} [get_ports gpio_bd[23]]      ; ## LD4
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W22   IOSTANDARD LVCMOS33} [get_ports gpio_bd[24]]      ; ## LD5
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U19   IOSTANDARD LVCMOS33} [get_ports gpio_bd[25]]      ; ## LD6
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U14   IOSTANDARD LVCMOS33} [get_ports gpio_bd[26]]      ; ## LD7
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[27]]      ; ## XADC-GIO0
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[28]]      ; ## XADC-GIO1
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[29]]      ; ## XADC-GIO2
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J15   IOSTANDARD LVCMOS25} [get_ports gpio_bd[30]]      ; ## XADC-GIO3
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G17   IOSTANDARD LVCMOS25} [get_ports gpio_bd[31]]      ; ## OTG-RESETN
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:SCOPED_XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G13" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D7" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A13" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:3 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:3 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:3 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B6" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G7" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C4" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A3" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N7" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:3 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M7" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:3 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R5" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F3" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W2" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G1" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:3 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:3 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:3 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:3 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:3 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U1" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA3" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:3 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:3 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:3 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:3 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:3 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:3 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA2" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P6" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:3 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N4" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:3 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:3 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M6" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L6" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L7" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J6" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J7" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K5" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K6" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:3 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
set_property src_info {type:SCOPED_XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:SCOPED_XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:SCOPED_XDC file:6 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_i2s_adi/S_AXI_ACLK]] -to [get_cells -hier out_data_reg* -filter {PRIMITIVE_SUBGROUP == flop && NAME =~ *tx_sync*}] [get_property PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_i2s_adi/DATA_CLK_I]]] -datapath_only
set_property src_info {type:SCOPED_XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_i2s_adi/DATA_CLK_I]] -to [get_cells -hier out_data_reg* -filter {PRIMITIVE_SUBGROUP == flop && NAME =~ *rx_sync*}] [get_property PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_i2s_adi/S_AXI_ACLK]]] -datapath_only
set_property src_info {type:SCOPED_XDC file:7 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_src_request_id* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_req_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *eot_mem_reg* -filter {NAME =~ *i_request_arb* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] -to [get_cells -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_req_response_id* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_response_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *eot_mem_reg* -filter {NAME =~ *i_request_arb* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_fifo/i_address_gray/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/m_src_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_fifo/i_address_gray/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9122_dma/fifo_rd_clk]]]
set_property src_info {type:SCOPED_XDC file:8 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_src_request_id* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]]]
set_property src_info {type:SCOPED_XDC file:8 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_req_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]]]
set_property src_info {type:SCOPED_XDC file:8 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *eot_mem_reg* -filter {NAME =~ *i_request_arb* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/fifo_wr_clk]]]
set_property src_info {type:SCOPED_XDC file:8 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]] -to [get_cells -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_req_response_id* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_waddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_raddr_sync* && PRIMITIVE_SUBGROUP == flop}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_response_fifo* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *eot_mem_reg* -filter {NAME =~ *i_request_arb* && PRIMITIVE_SUBGROUP == flop}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9643_dma/m_dest_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:9 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier *din_waddr_rel* -filter {primitive_subgroup == flop}] -to [get_cells -hier *dout_waddr_rel* -filter {primitive_subgroup == flop}]  8
